### DISCUSSION TITLE
全局代理时，真实ip地址通过webrtc泄露

### DISCUSSION THREAD

**Discussion by UchihaYuki** [vernesong/OpenClash#1976] [Q&A] [answered]
准确来说也不是“全局代理”，如下是我的部分配置：
```
proxy-groups:
  - name: pc
    type: socks5
    server: xxx
    port: xxx
    username: xxx
    password: xxx
    udp: true
rules:
  - SRC-IP-CIDR,192.168.31.122/32,pc
```
按理来说我电脑发出的所有tcp，udp都会被代理，不明白是怎么泄露的，我路由器是openwrt，感觉应该是用了tcp，udp以外的通信，有什么办法可以把除了udp，tcp的所有外网访问都block吗？这样做能100%防止泄露吗？
