### DISCUSSION TITLE
match_provider不起作用

### DISCUSSION THREAD

**Discussion by Zesshi-Zetsumei** [vernesong/OpenClash#2616] [Q&A]
想实现一个功能，让电视的奈飞和其他设备的奈飞走不同的策略组，需要根据内网ip进行分流，但不知为何match_provider不起作用
```yaml
script:
  shortcuts:
    test: src_ip == "192.168.8.248" and match_provider("Netflix")
    
rules:
  - SCRIPT,test,REJECT,no-resolve
```
在自定义规则里添加上述规则后，电脑仍然可以打开Netflix.com，已经确认ip地址无误，Netflix规则集也已是最新
