### DISCUSSION TITLE
[求助]使用公司VPN内网地址无法解析

### DISCUSSION THREAD

**Discussion by cuminlo** [vernesong/OpenClash#2640] [Q&A] [answered]
### VPN
公司使用的是飞连VPN，连上后是这样的显示
![image](https://user-images.githubusercontent.com/4970189/185676342-194c957b-c0d6-49fc-b7e0-71e418e891d5.png)

公司内网域名：`gitlab.gongsi.com`

在关闭 clash 的情况下，是可以访问公司内网的。

### 不使用 clash dns

```
nslookup gitlab.gongsi.com 223.5.5.5
服务器:  public1.alidns.com
Address:  223.5.5.5

非权威应答:
名称:    gitlab.gongsi.com
Address:  10.1.4.46
```

### 使用 clash dns

```
nslookup gitlab.gongsi.com 192.168.50.1
服务器:  OpenWrt.lan  
Address:  192.168.50.1

*** 没有 gitlab.gongsi.com 可以使用的 internal type for both IPv4 and IPv6 Addresses (A+AAAA)记
```

### clash 主要配置文件

```
mixed-port: 7893
socks-port: 7891
allow-lan: true
bind-address: "*"
ipv6: false
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:7874
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  - 180.76.76.76
  nameserver-policy:
    "+.gongsi.com": 223.5.5.5
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fake-ip-filter:
  - "+.synology.me"
  - "+.synology.com"
  - "*.tencentcdb.com"
```

真的试了往上说的好多方法，都行不通，实在是受不了了，求助各位大佬有空帮忙看下，请大佬喝可乐。
