### DISCUSSION TITLE
旁路网关开启FAKEIP纯TUN模式无法访问互联网，请问该如何排查问题？

### DISCUSSION THREAD

**Discussion by ghost** [vernesong/OpenClash#2756] [Q&A]
之前一直在 windows 环境使用的 CFW，开启 tun 如下配置。 
```
tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
```

近日想更换到 openwrt 上的 openclash，因为网不是一个人用所以考虑旁路网关的方式只代理部分设备。
计划通过 VmwareWorkstation16 尝鲜，固件是 esir 基于 lean 的高大全 2022 夏季版本，启动后配置好接口只开启 openclash
拿手机进行测试，网关设置为 Vmware 桥接网卡的 ip，DNS 保持默认的 8.8.8.8

openclash 默认模式代理正常√
切换到 FakeIP 正常√
切换到 TUN 混合模式正常√
切换到纯 TUN 失败，具体表现为直接断网，国内国外均无法访问。

怀疑是 tun 没有正常启用，检查被修改的配置文件里没有 tun 的字样，只有 enhanced mode
以下是纯 tun 模式的 DNS，此时路由器自己也无法连接 baidu/youtube
![image](https://user-images.githubusercontent.com/59040858/196786799-53a89d9e-b943-4ba7-af7a-87818698b6ee.png)

以下是混合模式的 DNS 查询，这时候能正常连网和代理。
![image](https://user-images.githubusercontent.com/59040858/196787045-0fc7dac4-714a-4b48-a5a5-f28811c27518.png)
