### DISCUSSION TITLE
Internet traffic from my router isn't redirected through VPN IP, why ?

### DISCUSSION THREAD

**Discussion by hillz2** [vernesong/OpenClash#2865] [Q&A]
I have openclash installed on my openwrt router (address at 192.168.1.1), all clients's traffics go through VPN just fine but when I do the command `curl ifconfig.me` on my router it shows my real IP instead of the VPN's IP. I want the internet on my router to go through the VPN's IP as well.

Here's the YACD log:
![2022-11-30-150759_1224x403_scrot](https://user-images.githubusercontent.com/25127225/204741615-d762b630-7272-40ce-9eff-499f87633974.png)

As you can see `ifconfig.me` matches `DIRECT` on the picture above, it should match my proxy-provider rule instead of `DIRECT`

Here's my `config.yaml` file:
```
---
proxy-providers:
  BugAkrab:
    type: file
    path: "./proxy_provider/BugAkrab.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 150
#  BugFlex:
#    type: file
#    path: "./proxy_provider/BugFlex.yaml"
#    health-check:
#      enable: true
#      url: http://www.gstatic.com/generate_204
#      interval: 150
  Game:
    type: file
    path: "./proxy_provider/Game.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 150

proxy-groups:
- name: BugAkrab
  type: load-balance #url-test
  strategy: consistent-hashing
  disable-udp: false
  use:
  - BugAkrab
  url: http://www.gstatic.com/generate_204
  interval: '150'
#- name: BugFlex
#  type: load-balance #url-test
#  strategy: consistent-hashing
#  disable-udp: false
#  use:
#  - BugFlex
#  url: http://www.gstatic.com/generate_204
#  interval: '150'
- name: Game
  type: load-balance #url-test
  strategy: consistent-hashing
  disable-udp: false
  use:
  - Game
  url: http://www.gstatic.com/generate_204
  interval: '150'
- name: Manual
  type: select
  strategy: consistent-hashing
  disable-udp: false
  use:
  - BugAkrab
#  - BugFlex
  - Game
  url: http://www.gstatic.com/generate_204
  interval: '150'

redir-port: 7892
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: debug
allow-lan: true
external-controller: 0.0.0.0:9090
secret: hashtag
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  listen: 127.0.0.1:5054
  default-nameserver:
  - 114.114.114.114
  - 8.8.8.8
  nameserver:
  - 8.8.8.8
  - 8.8.4.4
  - 1.1.1.1
  - 1.0.0.1
  - 9.9.9.9
  - 149.112.112.112
  - 208.67.222.222
  - 208.67.220.220
  - 185.228.168.9
  - 185.228.169.168
  - 76.76.2.0
  - 76.76.10.0
  - 94.140.14.140
  - 94.140.14.141
  - 172.105.216.54
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - "*.lan"
  - time.windows.com
  - time.nist.gov
  - time.apple.com
  - time.asia.apple.com
  - "*.ntp.org.cn"
  - "*.openwrt.pool.ntp.org"
  - time1.cloud.tencent.com
  - time.ustc.edu.cn
  - pool.ntp.org
  - ntp.ubuntu.com
  - ntp.aliyun.com
  - ntp1.aliyun.com
  - ntp2.aliyun.com
  - ntp3.aliyun.com
  - ntp4.aliyun.com
  - ntp5.aliyun.com
  - ntp6.aliyun.com
  - ntp7.aliyun.com
  - time1.aliyun.com
  - time2.aliyun.com
  - time3.aliyun.com
  - time4.aliyun.com
  - time5.aliyun.com
  - time6.aliyun.com
  - time7.aliyun.com
  - "*.time.edu.cn"
  - time1.apple.com
  - time2.apple.com
  - time3.apple.com
  - time4.apple.com
  - time5.apple.com
  - time6.apple.com
  - time7.apple.com
  - time1.google.com
  - time2.google.com
  - time3.google.com
  - time4.google.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "*.msftconnecttest.com"
  - "*.msftncsi.com"
  - localhost.ptlogin2.qq.com
  - "+.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.microsoft.com
  - "+.xboxlive.com"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "+.battlenet.com.cn"
  fallback-filter:
    geoip: false
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
    domain:
    - "+.google.com"
    - "+.facebook.com"
    - "+.youtube.com"
    - "+.githubusercontent.com"
ipv6: false
profile:
  store-selected: true
  store-fakeip: true
  store-fake-ip: true
rule-providers:
  adblock_energized_blu:
    type: http
    behavior: classical
    path: "./rule_provider/energized_blu_adblock.yaml"
    url: https://raw.githubusercontent.com/hillz2/openclash_adblock/main/energized_blu_adblock.yaml
    interval: 14400 # Update rules every 4 hours
rules:
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- DOMAIN-SUFFIX,local,DIRECT
- DOMAIN-SUFFIX,tencent.com,DIRECT

# Block ads
- RULE-SET,adblock_energized_blu,REJECT
#- RULE-SET,adblock_abpindo_annoyance,REJECT

# Games
# Mihoyo Games
- DOMAIN-SUFFIX,genshinimpact.com,Game
- DOMAIN-SUFFIX,honkaiimpact3.com,Game
- DOMAIN-SUFFIX,honkaistarrail.com,Game
- DOMAIN-SUFFIX,hoyo.link,Game
- DOMAIN-SUFFIX,hoyolab.com,Game
- DOMAIN-SUFFIX,hoyoverse.com,Game
- DOMAIN-SUFFIX,n0vadesktop.com,Game
- DOMAIN-SUFFIX,mihoyo.com,Game

# Whatsapp direct
- DOMAIN-SUFFIX,fna.whatsapp.net,DIRECT
- DOMAIN-SUFFIX,wa.me,DIRECT
- DOMAIN-SUFFIX,whatsapp-plus.info,DIRECT
- DOMAIN-SUFFIX,whatsapp-plus.me,DIRECT
- DOMAIN-SUFFIX,whatsapp-plus.net,DIRECT
- DOMAIN-SUFFIX,whatsapp.cc,DIRECT
- DOMAIN-SUFFIX,whatsapp.com,DIRECT
- DOMAIN-SUFFIX,whatsapp.info,DIRECT
- DOMAIN-SUFFIX,whatsapp.net,DIRECT
- DOMAIN-SUFFIX,whatsapp.org,DIRECT
- DOMAIN-SUFFIX,whatsapp.tv,DIRECT
- DOMAIN-SUFFIX,whatsappbrand.com,DIRECT
- DST-PORT,3478,DIRECT
- DST-PORT,4244,DIRECT
- DST-PORT,5222,DIRECT
- DST-PORT,5223,DIRECT
- DST-PORT,5228,DIRECT
- DST-PORT,5288,DIRECT
- DST-PORT,5242,DIRECT
- DST-PORT,5349,DIRECT
- DST-PORT,34784,DIRECT
- DST-PORT,45395,DIRECT
- DST-PORT,50318,DIRECT
- DST-PORT,59234,DIRECT
- DST-PORT,12222,DIRECT
- DST-PORT,11112,DIRECT
- DST-PORT,25566,DIRECT

# LAN should be on DIRECT
- IP-CIDR,0.0.0.0/8,DIRECT,no-resolve
- IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
- IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
- IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
- IP-CIDR,169.254.0.0/16,DIRECT,no-resolve
- IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
- IP-CIDR,192.0.0.0/24,DIRECT,no-resolve
- IP-CIDR,192.0.2.0/24,DIRECT,no-resolve
- IP-CIDR,192.88.99.0/24,DIRECT,no-resolve
- IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
- IP-CIDR,198.18.0.0/15,DIRECT,no-resolve
- IP-CIDR,198.51.100.0/24,DIRECT,no-resolve
- IP-CIDR,203.0.113.0/24,DIRECT,no-resolve
- IP-CIDR,224.0.0.0/3,DIRECT,no-resolve
- IP-CIDR,::1/128,DIRECT,no-resolve
- IP-CIDR,fc00::/7,DIRECT,no-resolve
- IP-CIDR,fe80::/10,DIRECT,no-resolve
- MATCH,GLOBAL
tun:
  enable: true
  auto-route: true
  stack: system
  dns-hijack:
  - any:53
  - tcp://any:53

```

Can you help me fix it ?
