### DISCUSSION TITLE
某域名只想解析成ipv4，该怎么做？

### DISCUSSION THREAD

**Discussion by Declarcall** [vernesong/OpenClash#2950] [Q&A]
不想关闭全局 ipv6 dns解析，只想对某域名强制(该域名确实有v4和v6的解析)解析成v4返回。

例如 我想通过 fast.com 测个速， api.fast.com (如果解析成v6 会报403，解析成v4则不会，感觉openclash在 Redir-Host 模式下解析 v6 会有各种问题？) 如何配置？

旁路由运行模式 为 Redir-Host (TUN)  运行 sudo apt update 时会报如下 Err :

```
$ sudo apt update
Ign:1 https://typora.io/linux ./ InRelease                               
Err:2 https://typora.io/linux ./ Release                                 
  Could not handshake: Error in the pull function. [IP: 2606:4700:20::ac43:6152 443]
...
```

如果切换为本地 clash 代理则不会有上述问题

若是切换成 Fake-IP 模式， fast.com 倒是可以正常测速了，但是 apt update (日常所用系统为Ubuntu) 却无法正常工作了，因为dns返回的是fakeip。有没有比较完美的解决办法呢？

---

找到个可行的方法，不过，略麻烦。就是在Fake-IP 模式下，进入 全局设置 - DNS设置 - 高级设置 - DNS 高级设置 （每行请只填写一个域名，列表中的域名在（Fake-IP模式）下查询DNS时将返回真实IP地址）， 把 apt list 里所有需要更新的域名都填进去， 以后如果需要新增 apt list 同样需要手动更新。

还有就是，在本机再开个 clash 或其他什么代理，让 apt 走那个代理（那还有什么必要用openclash (笑) ）。

**Comment by blizzardwj** [comment]
老铁解决这个问题了吗？我也有类似的问题，某个域名解析成ipv6之后会被ban，但解析成ipv4就没有这个问题。但是关闭openclash的ipv6 dns，PT下载又出问题了，tracker无法获得我的ipv6地址。真是头大。

**Comment by ghost** [comment]
meta倒是有个类似的功能 https://wiki.metacubex.one/config/proxies/#ip-version 虽然不是一步到位

**Reply by mwnu** [reply]
请问下在哪里配置这个选项？

**Reply by ghost** [reply]
这是内核的功能， OpenClash 插件设置启用 Meta 内核，然后改yaml文件，需要自己加ipv4专用节点。再把需要强制ipv4的规则指向这个节点。配置起来有点麻烦。
```yaml
proxies:
  - {name: ipv4, server: 127.0.0.1, port: 12345, type: ss, cipher: aes-128-gcm, password: password, udp: true, ip-version: ipv4}
proxy-groups:
  - name: i-p-v-4
    type: select
    proxies:
      - ipv4
rules:
 - DOMAIN,ipv4-only-url,i-p-v-4
```
