### DISCUSSION TITLE
I cannot get redir-host to work on OpenWRT

### DISCUSSION THREAD

**Discussion by hadifarnoud** [vernesong/OpenClash#3047] [General]
I have a DNS server (Pihole) behind OpenClash. In order to make it work someone told me I had to use redir-host. I now have DNS poisoning issue. can you help me fix my config? or is there a setting I messed up?

this is my config:
```
proxy-providers:
  all:
    type: http
    path: ./proxy_provider/servers.yaml
    url: https://gist.githubusercontent.com/**********/raw/servers.yaml
    interval: 3600
    health-check:
      enable: true
      url: 'http://www.gstatic.com/generate_204'
      interval: 500
proxy-groups:
  - name: Auto - UrlTest
    type: url-test
    use:
      - all
    url: 'http://www.gstatic.com/generate_204'
    interval: '600'
    tolerance: '300'
  - name: Proxy
    type: select
    use:
      - all
    proxies:
      - Auto - UrlTest
      - Proxy-fallback
      - DIRECT
  - name: Proxy-fallback
    type: fallback
    use:
      - all
    proxies:
      - Auto - UrlTest
  - name: Domestic
    type: select
    proxies:
      - DIRECT
      - Proxy
  - name: Others
    type: select
    proxies:
      - Proxy
      - DIRECT
      - Domestic
  - name: Microsoft
    type: select
    proxies:
      - DIRECT
      - Proxy
  - name: Apple
    type: select
    proxies:
      - DIRECT
      - Proxy
  - name: Google FCM
    type: select
    proxies:
      - DIRECT
      - Proxy
  - name: Scholar
    type: select
    proxies:
      - DIRECT
      - Proxy
  - name: Bilibili
    type: select
    proxies:
      - Asian TV
      - DIRECT
  - name: Bahamut
    type: select
    proxies:
      - Global TV
      - DIRECT
  - name: HBO Max
    type: select
    proxies:
      - Global TV
      - DIRECT
  - name: HBO Go
    type: select
    proxies:
      - Global TV
      - DIRECT
  - name: Pornhub
    type: select
    proxies:
      - Global TV
      - DIRECT
  - name: Netflix
    type: select
    proxies:
      - Global TV
      - DIRECT
  - name: Disney
    type: select
    proxies:
      - Global TV
      - DIRECT
  - name: Youtube
    type: select
    disable-udp: true
    proxies:
      - Global TV
      - DIRECT
  - name: Discovery Plus
    type: select
    proxies:
      - Global TV
      - DIRECT
  - name: DAZN
    type: select
    proxies:
      - Global TV
      - DIRECT
  - name: Spotify
    type: select
    proxies:
      - Global TV
      - DIRECT
  - name: Steam
    type: select
    proxies:
      - DIRECT
      - Proxy
  - name: AdBlock
    type: select
    proxies:
      - REJECT
      - DIRECT
      - Proxy
  - name: Asian TV
    type: select
    proxies:
      - DIRECT
      - Proxy
  - name: Global TV
    type: select
    proxies:
      - Proxy
      - DIRECT
  - name: Speedtest
    type: select
    proxies:
      - Proxy
      - DIRECT
  - name: Telegram
    type: select
    proxies:
      - Proxy
      - DIRECT
  - name: Crypto
    type: select
    proxies:
      - Proxy
      - DIRECT
  - name: Discord
    type: select
    proxies:
      - Proxy
      - DIRECT
  - name: PayPal
    type: select
    proxies:
      - DIRECT
      - Proxy
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: debug
allow-lan: true
external-controller: '0.0.0.0:9090'
secret: ''
bind-address: '*'
geodata-mode: true
geodata-loader: standard
tcp-concurrent: true
#tun:
#  enable: true
#  stack: gvisor
#  dns-hijack:
#    - 'any:53'
#  auto-route: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: '0.0.0.0:7874'
  nameserver:
    - 'https://dns.acamedium.com/dns-query'
    - 109.71.254.155
    - 8.8.8.8
    - 114.114.114.114
    - 119.29.29.29
    - 223.5.5.5
    - 'https://doh.pub/dns-query'
    - 'https://223.5.5.5/dns-query'
  fallback:
    - 'tls://1.1.1.1:853'
    - 'tls://dns.google'
  fallback-filter:
    geoip: true
    geoip-code: IR
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - +.google.com
      - +.facebook.com
      - +.youtube.com
      - +.githubusercontent.com
      - +.googlevideo.com
      - +.msftconnecttest.com
      - +.msftncsi.com
      - msftconnecttest.com
      - msftncsi.com
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time-ios.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - music.163.com
    - '*.music.163.com'
    - '*.126.net'
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - '*.kuwo.cn'
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - '*.y.qq.com'
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - '*.kamva.ir'
    - '*.xiami.com'
    - '*.music.migu.cn'
    - music.migu.cn
    - +.msftconnecttest.com
    - +.msftncsi.com
    - msftconnecttest.com
    - msftncsi.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - +.srv.nintendo.net
    - '*.n.n.srv.nintendo.net'
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - '*.*.xboxlive.com'
    - xbox.*.microsoft.com
    - xnotify.xboxlive.com
    - +.battlenet.com.cn
    - +.wotgame.cn
    - +.wggames.cn
    - +.wowsgame.cn
    - +.wargaming.net
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - stun1.*.*.*
    - stun2.*.*.*
    - stun3.*.*.*
    - stun4.*.*.*
    - stun5.*.*.*
    - '*.hivepal.com'
    - '*.ROOT-SERVERS.NET'
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - heartbeat.belkin.com
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - '*.router.asus.com'
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - lens.l.google.com
    - stun.l.google.com
    - +.nflxvideo.net
    - '*.square-enix.com'
    - '*.finalfantasyxiv.com'
    - '*.ffxiv.com'
    - '*.ff14.sdo.com'
    - ff.dorado.sdo.com
    - '*.mcdn.bilivideo.cn'
    - +.media.dssott.com
    - shark007.net
    - +.cmbchina.com
    - +.cmbimg.com
    - +.dns.google
    - accounts.google.com
    - apis.google.com
    - meetings.googleapis.com
    - meet.google.com
    - apps.google.com
    - jamboard.google.com
    - docs.google.com
    - stream.meet.google.com
    - youtube.googleapis.com
sniffer:
  enable: true
  sniffing:
    - tls
    - http
  ForceDnsMapping: false
  ParsePureIp: true
profile:
  store-selected: true
  store-fake-ip: true
rule-providers:
  Reject:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Reject.yaml
    path: ./rule_provider/Reject
    interval: 86400
  Special:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Special.yaml
    path: ./rule_provider/Special
    interval: 86400
  Netflix:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Netflix.yaml
    path: ./rule_provider/Netflix
    interval: 86400
  Spotify:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Spotify.yaml
    path: ./rule_provider/Spotify
    interval: 86400
  YouTube:
    type: http
    behavior: classical
    path: /etc/openclash/rule_provider/YouTube.yaml
    url: >-
      https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Video/YouTube.yaml
    interval: 86400
  Bilibili:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Bilibili.yaml
    path: ./rule_provider/Bilibili
    interval: 86400
  IQ:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/IQ.yaml
    path: ./rule_provider/IQI
    interval: 86400
  IQIYI:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/IQIYI.yaml
    path: ./rule_provider/IQYI
    interval: 86400
  Letv:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Letv.yaml
    path: ./rule_provider/Letv
    interval: 86400
  Netease Music:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Netease%20Music.yaml
    path: ./rule_provider/Netease_Music
    interval: 86400
  Tencent Video:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Tencent%20Video.yaml
    path: ./rule_provider/Tencent_Video
    interval: 86400
  Youku:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Youku.yaml
    path: ./rule_provider/Youku
    interval: 86400
  WeTV:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/WeTV.yaml
    path: ./rule_provider/WeTV
    interval: 86400
  ABC:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/ABC.yaml
    path: ./rule_provider/ABC
    interval: 86400
  Abema TV:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Abema%20TV.yaml
    path: ./rule_provider/Abema_TV
    interval: 86400
  Amazon:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Amazon.yaml
    path: ./rule_provider/Amazon
    interval: 86400
  Apple Music:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Apple%20Music.yaml
    path: ./rule_provider/Apple_Music
    interval: 86400
  Apple News:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Apple%20News.yaml
    path: ./rule_provider/Apple_News
    interval: 86400
  Apple TV:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Apple%20TV.yaml
    path: ./rule_provider/Apple_TV
    interval: 86400
  Bahamut:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Bahamut.yaml
    path: ./rule_provider/Bahamut
    interval: 86400
  BBC iPlayer:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/BBC%20iPlayer.yaml
    path: ./rule_provider/BBC_iPlayer
    interval: 86400
  DAZN:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/DAZN.yaml
    path: ./rule_provider/DAZN
    interval: 86400
  Discovery Plus:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Discovery%20Plus.yaml
    path: ./rule_provider/Discovery_Plus
    interval: 86400
  Disney Plus:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Disney%20Plus.yaml
    path: ./rule_provider/Disney_Plus
    interval: 86400
  encoreTVB:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/encoreTVB.yaml
    path: ./rule_provider/encoreTVB
    interval: 86400
  F1 TV:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/F1%20TV.yaml
    path: ./rule_provider/F1_TV
    interval: 86400
  Fox Now:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Fox%20Now.yaml
    path: ./rule_provider/Fox_Now
    interval: 86400
  Fox+:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Fox%2B.yaml
    path: ./rule_provider/Fox+
    interval: 86400
  HBO Go:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/HBO%20Go.yaml
    path: ./rule_provider/HBO_Go
    interval: 86400
  HBO Max:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/HBO%20Max.yaml
    path: ./rule_provider/HBO_Max
    interval: 86400
  Hulu Japan:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Hulu%20Japan.yaml
    path: ./rule_provider/Hulu_Japan
    interval: 86400
  Hulu:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Hulu.yaml
    path: ./rule_provider/Hulu
    interval: 86400
  Japonx:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Japonx.yaml
    path: ./rule_provider/Japonx
    interval: 86400
  JOOX:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/JOOX.yaml
    path: ./rule_provider/JOOX
    interval: 86400
  KKBOX:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/KKBOX.yaml
    path: ./rule_provider/KKBOX
    interval: 86400
  KKTV:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/KKTV.yaml
    path: ./rule_provider/KKTV
    interval: 86400
  Line TV:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Line%20TV.yaml
    path: ./rule_provider/Line_TV
    interval: 86400
  myTV SUPER:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/myTV%20SUPER.yaml
    path: ./rule_provider/myTV_SUPER
    interval: 86400
  Pandora:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Pandora.yaml
    path: ./rule_provider/Pandora
    interval: 86400
  PBS:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/PBS.yaml
    path: ./rule_provider/PBS
    interval: 86400
  Pornhub:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Pornhub.yaml
    path: ./rule_provider/Pornhub
    interval: 86400
  Soundcloud:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/Soundcloud.yaml
    path: ./rule_provider/Soundcloud
    interval: 86400
  ViuTV:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Media/ViuTV.yaml
    path: ./rule_provider/ViuTV
    interval: 86400
  Telegram:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Telegram.yaml
    path: ./rule_provider/Telegram
    interval: 86400
  Crypto:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Crypto.yaml
    path: ./rule_provider/Crypto
    interval: 86400
  Discord:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Discord.yaml
    path: ./rule_provider/Discord
    interval: 86400
  Steam:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Steam.yaml
    path: ./rule_provider/Steam
    interval: 86400
  Speedtest:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Speedtest.yaml
    path: ./rule_provider/Speedtest
    interval: 86400
  PayPal:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/PayPal.yaml
    path: ./rule_provider/PayPal
    interval: 86400
  Microsoft:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Microsoft.yaml
    path: ./rule_provider/Microsoft
    interval: 86400
  PROXY:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Proxy.yaml
    path: ./rule_provider/Proxy
    interval: 86400
  Domestic:
    type: http
    behavior: classical
    url: >-
      https://raw.githubusercontent.com/hadifarnoud/clash-config/main/Domestic.yaml
    path: ./rule_provider/Domestic
    interval: 86400
  Kamva:
    type: http
    behavior: classical
    url: 'https://raw.githubusercontent.com/hadifarnoud/clash-config/main/Kamva.yaml'
    path: ./rule_provider/Kamva
    interval: 86400
  Apple:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Apple.yaml
    path: ./rule_provider/Apple
    interval: 86400
  Google FCM:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Google%20FCM.yaml
    path: ./rule_provider/Google FCM
    interval: 86400
  Scholar:
    type: http
    behavior: classical
    url: >-
      https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/Scholar.yaml
    path: ./rule_provider/Scholar
    interval: 86400
  Domestic IPs:
    type: http
    behavior: ipcidr
    url: >-
      https://raw.githubusercontent.com/hadifarnoud/clash-config/main/Domestic%20IPs.yaml
    path: ./rule_provider/Domestic_IPs
    interval: 86400
  Iran:
    type: http
    behavior: classical
    url: >-
      https://github.com/chiroots/iran-hosted-domains/releases/latest/download/clash_rules.yaml
    path: ./rule_provider/Iran
    interval: 86400
  LAN:
    type: http
    behavior: classical
    url: 'https://fastly.jsdelivr.net/gh/dler-io/Rules@main/Clash/Provider/LAN.yaml'
    path: ./rule_provider/LAN
    interval: 86400
script:
  code: |
    def main(ctx, metadata):
        ruleset_action = {"Reject": "AdBlock",
            "Special": "DIRECT",
            "Netflix": "Netflix",
            "Spotify": "Spotify",
            "YouTube": "Youtube",
            "Disney Plus": "Disney",
            "Bilibili": "Bilibili",
            "IQ": "Asian TV",
            "IQIYI": "Asian TV",
            "Letv": "Asian TV",
            "Netease Music": "Asian TV",
            "Tencent Video": "Asian TV",
            "Youku": "Asian TV",
            "WeTV": "Asian TV",
            "ABC": "Global TV",
            "Abema TV": "Global TV",
            "Amazon": "Global TV",
            "Apple Music": "Global TV",
            "Apple News": "Global TV",
            "Apple TV": "Global TV",
            "Bahamut": "Bahamut",
            "BBC iPlayer": "Global TV",
            "DAZN": "DAZN",
            "Discovery Plus": "Discovery Plus",
            "encoreTVB": "Global TV",
            "F1 TV": "Global TV",
            "Fox Now": "Global TV",
            "Fox+": "Global TV",
            "HBO Go": "HBO Go",
            "HBO Max": "HBO Max",
            "Hulu Japan": "Global TV",
            "Hulu": "Global TV",
            "Japonx": "Global TV",
            "JOOX": "Global TV",
            "KKBOX": "Global TV",
            "KKTV": "Global TV",
            "Line TV": "Global TV",
            "myTV SUPER": "Global TV",
            "Pandora": "Global TV",
            "PBS": "Global TV",
            "Pornhub": "Pornhub",
            "Soundcloud": "Global TV",
            "ViuTV": "Global TV",
            "Telegram": "Telegram",
            "Crypto": "Crypto",
            "Discord": "Discord",
            "Steam": "Steam",
            "Speedtest": "Speedtest",
            "PayPal": "PayPal",
            "Microsoft": "Microsoft",
            "Apple": "Apple",
            "Google FCM": "Google FCM",
            "Scholar": "Scholar",
            "PROXY": "Proxy",
            "Kamva": "Domestic",
            "Domestic": "Domestic",
            "Domestic IPs": "Domestic",
            "LAN": "DIRECT"
          }

        port = int(metadata["dst_port"])

        if metadata["network"] == "UDP":
            if port == 443:
                ctx.log('[Script] matched QUIC traffic use reject')
                return "REJECT"

        port_list = [21, 22, 23, 53, 80, 123, 143, 194, 443, 465, 587, 853, 993, 995, 998, 2052, 2053, 2082, 2083, 2086, 2095, 2096, 5222, 5228, 5229, 5230, 8080, 8443, 8880, 8888, 8889]
        if port not in port_list:
            ctx.log('[Script] not common port use direct')
            return "DIRECT"

        if metadata["dst_ip"] == "":
            metadata["dst_ip"] = ctx.resolve_ip(metadata["host"])

        for ruleset in ruleset_action:
            if ctx.rule_providers[ruleset].match(metadata):
                return ruleset_action[ruleset]

        if metadata["dst_ip"] == "":
            return "DIRECT"

        code = ctx.geoip(metadata["dst_ip"])
        if code == "IR":
            ctx.log('[Script] Geoip irancells')
            return "Domestic"

        ctx.log('[Script] FINAL')
        return "Others"
rules:
  - 'DST-PORT,7895,REJECT'
  - 'DST-PORT,7892,REJECT'
  - 'IP-CIDR,198.18.0.1/16,REJECT,no-resolve'
  - 'RULE-SET,YouTube,Proxy'
  - 'RULE-SET,Reject,AdBlock'
  - 'RULE-SET,Special,DIRECT'
  - 'RULE-SET,Netflix,Netflix'
  - 'RULE-SET,Spotify,Spotify'
  - 'RULE-SET,YouTube,Youtube'
  - 'RULE-SET,Disney Plus,Disney'
  - 'RULE-SET,Bilibili,Bilibili'
  - 'RULE-SET,IQ,Asian TV'
  - 'RULE-SET,IQIYI,Asian TV'
  - 'RULE-SET,Letv,Asian TV'
  - 'RULE-SET,Netease Music,Asian TV'
  - 'RULE-SET,Tencent Video,Asian TV'
  - 'RULE-SET,Youku,Asian TV'
  - 'RULE-SET,WeTV,Asian TV'
  - 'RULE-SET,ABC,Global TV'
  - 'RULE-SET,Abema TV,Global TV'
  - 'RULE-SET,Amazon,Global TV'
  - 'RULE-SET,Apple Music,Global TV'
  - 'RULE-SET,Apple News,Global TV'
  - 'RULE-SET,Apple TV,Global TV'
  - 'RULE-SET,Bahamut,Bahamut'
  - 'RULE-SET,BBC iPlayer,Global TV'
  - 'RULE-SET,DAZN,DAZN'
  - 'RULE-SET,Discovery Plus,Discovery Plus'
  - 'RULE-SET,encoreTVB,Global TV'
  - 'RULE-SET,F1 TV,Global TV'
  - 'RULE-SET,Fox Now,Global TV'
  - 'RULE-SET,Fox+,Global TV'
  - 'RULE-SET,HBO Go,HBO Go'
  - 'RULE-SET,HBO Max,HBO Max'
  - 'RULE-SET,Hulu Japan,Global TV'
  - 'RULE-SET,Hulu,Global TV'
  - 'RULE-SET,Japonx,Global TV'
  - 'RULE-SET,JOOX,Global TV'
  - 'RULE-SET,KKBOX,Global TV'
  - 'RULE-SET,KKTV,Global TV'
  - 'RULE-SET,Line TV,Global TV'
  - 'RULE-SET,myTV SUPER,Global TV'
  - 'RULE-SET,Pandora,Global TV'
  - 'RULE-SET,PBS,Global TV'
  - 'RULE-SET,Pornhub,Pornhub'
  - 'RULE-SET,Soundcloud,Global TV'
  - 'RULE-SET,ViuTV,Global TV'
  - 'RULE-SET,Telegram,Telegram'
  - 'RULE-SET,Crypto,Crypto'
  - 'RULE-SET,Discord,Discord'
  - 'RULE-SET,Steam,Steam'
  - 'RULE-SET,Speedtest,Speedtest'
  - 'RULE-SET,PayPal,PayPal'
  - 'RULE-SET,Microsoft,Microsoft'
  - 'RULE-SET,Apple,Apple'
  - 'RULE-SET,Google FCM,Google FCM'
  - 'RULE-SET,Scholar,Scholar'
  - 'RULE-SET,PROXY,Proxy'
  - 'RULE-SET,Domestic,Domestic'
  - 'RULE-SET,Domestic IPs,Domestic'
  - 'RULE-SET,Iran,Domestic'
  - 'RULE-SET,Kamva,Domestic'
  - 'RULE-SET,LAN,DIRECT'
  - 'DOMAIN-SUFFIX,ir,DIRECT'
  - 'DOMAIN-SUFFIX,plex.direct,DIRECT'
  - 'DOMAIN-SUFFIX,cloudflare-ipfs.com,DIRECT'
  - 'GEOIP,IR,Domestic'
  - 'MATCH,Others'

```
