### DISCUSSION TITLE
DNS劫持问题

### DISCUSSION THREAD

**Discussion by aihoom** [vernesong/OpenClash#3057] [Q&A]
```
OpenClash 调试日志

生成时间: 2023-03-03 23:49:33
插件版本: 
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息



#===================== 系统信息 =====================#

主机型号: Raspberry Pi 4 Model B Rev 1.2
固件版本: OpenWrt 22.03.3 01.09.2023
LuCI版本: 
内核版本: 5.15.86
处理器架构: 

#此项有值时,如不使用IPv6,建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: hybrid

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#

dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
libcap: 已安装
libcap-bin: 已安装
ruby: 已安装
ruby-yaml: 已安装
ruby-psych: 已安装
ruby-pstore: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci >= 19.07): 已安装
kmod-inet-diag(PROCESS-NAME): 已安装
unzip: 已安装
iptables-mod-tproxy: 已安装
kmod-ipt-tproxy: 已安装
iptables-mod-extra: 已安装
kmod-ipt-extra: 已安装
kmod-ipt-nat: 已安装

#===================== 内核检查 =====================#

运行状态: 运行中
进程pid: 21530
运行权限: 21530: cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_ptrace,cap_sys_resource=eip
运行用户: nobody
已选择的架构: linux-arm64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2023.02.16-4-gfd54c76
Tun内核文件: 存在
Tun内核运行权限: 正常

Dev内核版本: v1.13.0-5-gf78a7cb
Dev内核文件: 存在
Dev内核运行权限: 正常

Meta内核版本: alpha-g245803d
Meta内核文件: 存在
Meta内核运行权限: 正常

#===================== 插件设置 =====================#

当前配置文件: /etc/openclash/config/Din.yaml
启动配置文件: /etc/openclash/Din.yaml
运行模式: fake-ip
默认代理模式: rule
UDP流量转发(tproxy): 启用
DNS劫持: Dnsmasq 转发
自定义DNS: 启用
IPV6代理: 启用
IPV6-DNS解析: 启用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 停用
仅代理命中规则流量: 启用
仅允许常用端口流量: 停用
绕过中国大陆IP: 启用
路由本机代理: 启用

#启动异常时建议关闭此项后重试
混合节点: 停用
保留配置: 停用

#启动异常时建议关闭此项后重试
第三方规则: 停用

#===================== 配置文件 =====================#

port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:7874
  enhanced-mode: fake-ip
  default-nameserver:
  - 119.29.29.29
  - 119.28.28.28
  - 1.0.0.1
  - 208.67.222.222
  - 1.2.4.8
  nameserver:
  - 114.114.114.114
  - 119.29.29.29
  - 119.28.28.28
  - 223.5.5.5
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fake-ip-range: 198.18.0.1/16
  fallback:
  - https://dns.cloudflare.com/dns-query
  - https://public.dns.iij.jp/dns-query
  - https://jp.tiar.app/dns-query
  - https://jp.tiarap.org/dns-query
  - tls://dot.tiar.app
 ```

以上是调试日志，我确保我只安装了openclash这一款软件内置的dnsmap-full依赖，其他的有关于DNS的只有AdGuard_Home还没有开启，一开始是面板有能嗅探到域名，但是国内访问如微信什么的巨慢！！！ 而且只有IOS才特别的慢 安卓还好点！ 所以关闭了DNS劫持，但同时导致的问题是DNS泄漏。  但是无论开启DNS还是关闭DNS劫持，我的DNS一直显示都是没有劫持成功。

如下测试 

```

Question: 
  Name: www.instagram.com.
  Qtype: 1
  Qclass: 1

Answer: 
  TTL: 337
  data: geo-p42.instagram.com.
  name: www.instagram.com.
  type: 5

  TTL: 337
  data: z-p42-instagram.c10r.instagram.com.
  name: geo-p42.instagram.com.
  type: 5

  TTL: 337
  data: 31.13.82.174
  name: z-p42-instagram.c10r.instagram.com.
  type: 1

```
我尝试用AdGuard_Home调用127.0.0.1:7874 但是提示我无法使用
