### DISCUSSION TITLE
openwrt 安装openclash 提示ruby 依赖异常

### DISCUSSION THREAD

**Discussion by ICLXL** [vernesong/OpenClash#3385] [Q&A]
![image](https://github.com/vernesong/OpenClash/assets/30027321/5b348cce-14ce-4478-abe7-558cc1791ee4)

![image](https://github.com/vernesong/OpenClash/assets/30027321/aee7f2d7-79de-40d3-8db0-cb17dd5df9f7)

**Comment by ghost** [comment]
装少了，截图里也提示了。

`插件设置-调试日志-生成日志` 里会显示全部的必备依赖

```yaml
dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
libcap: 已安装
libcap-bin: 已安装
ruby: 已安装
ruby-yaml: 已安装
ruby-psych: 已安装
ruby-pstore: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci >= 19.07): 已安装
kmod-inet-diag(PROCESS-NAME): 已安装
unzip: 已安装
iptables-mod-tproxy: 已安装
kmod-ipt-tproxy: 已安装
iptables-mod-extra: 已安装
kmod-ipt-extra: 已安装
kmod-ipt-nat: 已安装
```

另外，最近的 master 分支用 openclash  好像问题蛮多的
