### DISCUSSION TITLE
ERR_NAME_NOT_RESOLVED， twitter打不开，google可以访问

### DISCUSSION THREAD

**Discussion by linxingwu** [vernesong/OpenClash#3706] [Q&A]
youtube 能打开，但是获取不了封面，也无法播放。
twitter 打不开
google 可以访问
yacd无法连接

dev v1.18.0-13-gd034a40
tun 2023.08.17-13-gdcc8d87
meta alpha-gcc64297
客户端 v0.45.157-beta

#===================== 路由表状态 =====================#

#IPv4

#route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         100.90.0.1      0.0.0.0         UG    0      0        0 pppoe-wan
100.90.0.1      0.0.0.0         255.255.255.255 UH    0      0        0 pppoe-wan
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.100.0   0.0.0.0         255.255.255.0   U     0      0        0 br-lan

#ip route list
default via 100.90.0.1 dev pppoe-wan proto static 
100.90.0.1 dev pppoe-wan proto kernel scope link src *WAN IP*.96 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
192.168.100.0/24 dev br-lan proto kernel scope link src 192.168.100.1 

#ip rule show
0:	from all lookup local
32765:	from all fwmark 0x162 lookup 354
32766:	from all lookup main
32767:	from all lookup default

请教各位大佬，应该怎么修改配置还是有bug？

**Comment by ghost** [comment]
你说的哪里的 yacd 内置的还是网络上的？

另，你这个说明其实什么都看不出来，只能靠猜

**Reply by linxingwu** [reply]
内置的yacd打不开。
我有一个旧的订阅，当时使用dev内核就可以正常运行。后来换了一个reality/hysteria协议的机场。dev内核无法启动，于是全部更新了，换成我开头提到的版本。启用meta内核，此时新订阅可以工作。我想切换机场，于是退回dev内核，启用旧订阅。就会导致只有https://www.google.com能访问。google.com都会`ERR_NAME_NOT_RESOLVED`. 所以我感觉可能是meta内核和dev内核互相之间有影响，导致了DNS出问题了。 但是DNS我不太熟，所以把路由表贴上了。
请问我应该从哪里排查， 拿到哪个日志/配置呢？

**Reply by linxingwu** [reply]
clash配置文件
```yaml
hosts:
  mtalk.google.com: 108.177.125.188
  raw.githubusercontent.com: 151.101.76.133
dns:
  enabled: true
  ipv6: false
  listen: 0.0.0.0:7874
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver-policy:
    "*.google.com": 8.8.8.8
    "*.tw": 1.1.1.1
    testflight.apple.com: 8.8.8.8
    "*.tmall.com": 223.5.5.5
    "*.taobao.com": 223.5.5.5
    "*.alicdn.com": 223.5.5.5
    "*.aliyun.com": 223.5.5.5
    "*.alipay*.com": 223.5.5.5
    "*.alibaba*.com": 223.5.5.5
    "*.alimama*.com": 223.5.5.5
    "*.qq.com": 114.114.114.114
    "*.tencent.com": 114.114.114.114
    "*.weixin.com": 114.114.114.114
    "*.qpic.cn": 114.114.114.114
    "*.jd.com": 114.114.114.114
    "*.bilibili.com": 114.114.114.114
    hdslb.com: 114.114.114.114
    "*.163.com": 119.29.29.29
    "*.126.com": 119.29.29.29
    "*.126.net": 114.114.114.114
    "*.127.net": 114.114.114.114
    "*.netease.com": 114.114.114.114
    "*.10010.com": 114.114.114.114
    "*.unicompayment.com": 114.114.114.114
    "*.ximalaya.com": 114.114.114.114
    "*.baidu.com": 114.114.114.114
    "*.bdstatic.com": 114.114.114.114
  nameserver:
  - https://dns.alidns.com/dns-query
  fallback:
  - https://dns.cloudflare.com/dns-query
  - https://doh.mullvad.net/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - "+.*"
```
