### DISCUSSION TITLE
How to make OpenClash automatically resolve IPs to hostnames?

### DISCUSSION THREAD

**Discussion by turtle-ca-chan** [vernesong/OpenClash#4128] [Q&A]
Hello. I apologize for the probably stupid question, but I've been trying to find an answer by myself for a few days and decided it would be better to just ask more experienced people. I use an offline configuration file with rules for site domains, but for most connections OpenClash doesn't resolve IPs to domains and therefore the domains' rules are not applied. It is important to note that **OpenClash itself works fine** if I use it without rules or for IPs that can be resolved.
![screen](https://github.com/user-attachments/assets/984c3d50-9f85-4a16-ba9d-5afb9c3b806c)
I have rebooted both router and computer several times, and looked through almost every option in settings, but I could not find a solution on my own, neither in practice nor by searching. I also read general documentation (via translator). I have a hard time searching for my problem because I can only formulate a search query in English. I feel like I'm missing some simple detail because I'm just getting familiar with OpenClash.

My router is Xiaomi AX3000T (with ESMT NAND flash chip). Below I will give the contents of "Config File Edited By OpenClash For Running" and the current network & dhcp settings of OpenWrt.
```yaml
---
allow-lan: true
dns:
  enable: true
  listen: 0.0.0.0:7870 #dns port
  use-system-hosts: true
  default-nameserver:
  - https://1.1.1.1/dns-query
  - 1.1.1.1
  - 1.0.0.1
  - 208.67.222.222
  - 208.67.220.220
  - 208.67.222.220
  - 208.67.220.222
  - 172.104.237.57
  - 172.104.49.100
  - 37.235.1.174
  - 37.235.1.177
  - 45.33.97.5
  - 84.200.69.80
  - 84.200.70.40
  - 8.8.8.8
  - 8.8.4.4
  - 114.114.114.114
  fake-ip-filter-mode: whitelist
  nameserver:
  - https://1.1.1.1/dns-query
  - 1.1.1.1
  - 1.0.0.1
  - 208.67.222.222
  - 208.67.220.220
  - 208.67.222.220
  - 208.67.220.222
  - 172.104.237.57
  - 172.104.49.100
  - 37.235.1.174
  - 37.235.1.177
  - 45.33.97.5
  - 84.200.69.80
  - 84.200.70.40
  - 8.8.8.8
  - 8.8.4.4
  - 114.114.114.114
  ipv6: false
  enhanced-mode: redir-host
proxies:
- type: vless
  name: Proxy
  server: some_ip
  port: 443
  udp: true
  uuid: some_uuid
  tls: true
  servername: some_site
  flow: xtls-rprx-vision
  client-fingerprint: chrome
  skip-cert-verify: false
  reality-opts:
    public-key: some_key
    short-id: some_id
  ws-opts:
    v2ray-http-upgrade: true
    v2ray-http-upgrade-fast-open: true
  http-opts: {}
  grpc-opts: {}
  network: tcp
  smux:
    enabled: false
proxy-groups:
- type: select
  name: Test
  interval: 300
  timeout: 5000
  max-failed-times: 5
  lazy: true
  proxies:
  - Proxy
  - DIRECT
rules:
- DST-PORT,7892,REJECT
- DST-PORT,7891,REJECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- DOMAIN-REGEX,^(|(.*)\.)discord.co,Test
- DOMAIN-REGEX,(|(.*))discord.com,Test
- DOMAIN-REGEX,(|(.*))discord.gg,Test
- DOMAIN-REGEX,(|(.*))discordcdn.com,Test
- DOMAIN-REGEX,(|(.*))discordapp.com,Test
- DOMAIN-REGEX,(|(.*))discordapp.net,Test
- DOMAIN-REGEX,(|(.*))discord.media,Test
- DOMAIN-REGEX,(|(.*))discord.design,Test
- DOMAIN-REGEX,(|(.*))discord.dev,Test
- DOMAIN-REGEX,(|(.*))discord.gift,Test
- DOMAIN-REGEX,(|(.*))discord.gifts,Test
- DOMAIN-REGEX,(|(.*))discord.new,Test
- DOMAIN-REGEX,(|(.*))discord.store,Test
- DOMAIN-REGEX,(|(.*))discord.tools,Test
- DOMAIN-REGEX,(|(.*))discordmerch.com,Test
- DOMAIN-REGEX,(|(.*))discordpartygames.com,Test
- DOMAIN-REGEX,(|(.*))discord-activities.com,Test
- DOMAIN-REGEX,(|(.*))discordactivities.com,Test
- DOMAIN-REGEX,(|(.*))discordsays.com,Test
- DOMAIN-REGEX,(|(.*))discordstatus.com,Test
- DOMAIN-REGEX,(|(.*))discord-attachments-uploads-prd.storage.googleapis.com,Test
- DOMAIN-REGEX,(|.{0,2}\.)ytimg\.com,Test
- DOMAIN-REGEX,(.*)\.googlevideo\.com,Test
- DOMAIN-REGEX,(|www\.)youtube\.com,Test
- DOMAIN,youtu.be,Test
- DOMAIN,whatismyipaddress.com,Test
- DOMAIN,whoer.net,Test
- DOMAIN,browserleaks.com,Test
- DOMAIN-SUFFIX,torproject.org,Test
- DOMAIN-SUFFIX,ip.sb,Test
- DOMAIN-SUFFIX,pconline.com.cn,Test
- DOMAIN-SUFFIX,upaiyun.com,Test
- DOMAIN-SUFFIX,ipify.org,Test
- MATCH,PASS,no-resolve
redir-port: 7891
tproxy-port: 7892
port: 7893
socks-port: 7894
mixed-port: 7895
mode: rule
external-controller: 0.0.0.0:some_port
secret: some_secret
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
ipv6: false
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
tun:
  enable: true
  stack: system
  device: utun
  dns-hijack:
  - tcp://any:53
  gso: true
  gso-max-size: 65536
  auto-route: false
  auto-detect-interface: false
  auto-redirect: false
  strict-route: false
profile:
  store-selected: true
authentication:
- Test:testtesttest
```
OpenWrt's network file:
```bash
config interface 'loopback'
	option device 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config globals 'globals'
	option ula_prefix 'fd11:c02f:5717::/48'

config device
	option name 'br-lan'
	option type 'bridge'
	list ports 'lan2'
	list ports 'lan3'
	list ports 'lan4'
	option mtu '1452'

config interface 'lan'
	option device 'br-lan'
	option proto 'static'
	option ipaddr '192.168.2.1'
	option netmask '255.255.255.0'
	option ip6assign '60'

config device
	option name 'wan'
	option macaddr 'some_macaddr'
	option mtu '1452'

config interface 'wan'
	option device 'wan'
	option proto 'dhcp'
	option peerdns '0'
	list dns '1.1.1.1'
	list dns '1.0.0.1'
	list dns '8.8.8.8'
	list dns '8.8.4.4'
	list dns '208.67.222.222'
	list dns '208.67.220.220'
	list dns '208.67.222.220'
	list dns '208.67.220.222'
	list dns '172.104.237.57'
	list dns '172.104.49.100'
	list dns '37.235.1.174'
	list dns '37.235.1.177'
	list dns '45.33.97.5'
	list dns '84.200.69.80'
	list dns '84.200.70.40'
```
OpenWrt's dhcp file:
```bash
config dnsmasq
	option domainneeded '1'
	option localise_queries '1'
	option rebind_protection '1'
	option rebind_localhost '1'
	option local '/lan/'
	option domain 'lan'
	option expandhosts '1'
	option cachesize '0'
	option authoritative '1'
	option readethers '1'
	option leasefile '/tmp/dhcp.leases'
	option localservice '1'
	option ednspacket_max '1232'
	option filter_aaaa '1'
	option localuse '1'
	option noresolv '1'
	list server '127.0.0.1#7870'

config dhcp 'lan'
	option interface 'lan'
	option start '100'
	option limit '150'
	option leasetime '12h'
	option dhcpv4 'server'

config dhcp 'wan'
	option interface 'wan'
	option ignore '1'

config odhcpd 'odhcpd'
	option maindhcp '0'
	option leasefile '/tmp/hosts/odhcpd'
	option leasetrigger '/usr/sbin/odhcpd-update'
	option loglevel '4'
```

**I also disabled IPv6 everywhere**. I use 192.168.2.1 for LAN because I have two routers connected to each other. I use router without OpenWrt for WiFi and router with OpenWrt only for connection via ethernet cable and routing. I had no problems with the routers themselves. 
Otherwise my OpenWrt settings are standard. I'm using the latest stable version (23.05.5). Before installing OpenClash I used "miniupnpd" for some time (it is still installed).

I installed OpenClash in the following way:
```sh
opkg update
opkg install dnsmasq-full --download-only && opkg remove dnsmasq && opkg install dnsmasq-full --cache . && rm *.ipk
opkg install coreutils-nohup bash iptables dnsmasq-full curl ca-certificates ipset ip-full iptables-mod-tproxy iptables-mod-extra libcap libcap-bin ruby ruby-yaml kmod-tun kmod-inet-diag unzip luci-compat luci luci-base iptables iptables-mod-tproxy iptables-mod-extra
cd /tmp
wget -c "https://github.com/vernesong/OpenClash/releases/download/v0.46.033-beta/luci-app-openclash_0.46.033-beta_all.ipk"
opkg install luci-app-openclash_0.46.033-beta_all.ipk
```
