### DISCUSSION TITLE
如果不在config.yaml里配置dns，那代理服务器的域名由谁解析呢？

### DISCUSSION THREAD

**Discussion by UchihaYuki** [vernesong/OpenClash#4149] [Q&A]
在删除config.yaml里的dns配置之前，我所有的代理服务器在`Yacd 控制面板`里，都是有速度显示的。
删除之后部分代理服务器没有速度显示了。在局域网电脑里`nslookup proxy-server-domain`的返回结果如下：
```
Server:  router.lan
Address:  192.168.31.1

DNS request timed out.
    timeout was 2 seconds.
*** Request to router.lan timed-out
```
感觉是代理服务器域名解析失败了。

我的rules非常简单：
```
rules:
  - SRC-IP-CIDR,192.168.31.179/32,DIRECT 
  - SRC-IP-CIDR,192.168.31.149/32,DIRECT 
  - SRC-IP-CIDR,192.168.31.177/32,DIRECT 
  - MATCH,others
```
理论上，所有的域名解析（除了代理服务器的），都是直接发往代理服务器去解析的（至少我是这样理解的），但现在我所有的域名解析都失败了，除了百度这种国内的域名。

我是因为出现DNS泄露，然后发现不能再config.yaml里面指定dns，否则所有的域名解析都会用config.yaml里面指定的dns去解析，无法传到代理服务器，才把dns删掉的。不知道哪里理解错了。

**Comment by fejeIaqbhbv** [comment]
OpenClash启动时缺少dns会自动添加，你怎么删掉的？

既然你的rule这么简单，又怕所谓的dns泄露，那不如
```yaml
dns:
  nameserver:
  - https://dns.cloudflare.com/dns-query#代理节点
  - https://dns.google/dns-query#代理节点
  use-hosts: true
hosts:
 代理节点域名:代理节点ip
```
