### DISCUSSION TITLE
Openclash DNS 解析的流程具体是怎么走的？为什么同样的 DNS 配置适用于 cfw 却不适用 openclash？

### DISCUSSION THREAD

**Discussion by Starseeker-H** [vernesong/OpenClash#4221] [Q&A]
首先是出于未知原因，走路由器的设备国外域名都解析不到ip了，但被我更换了meta内核的 clash of windows 可以正常访问，且两者的 DNS 配置都是
```
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
  - 114.114.114.114
  - 119.29.29.29
  - 223.5.5.5
  - https://doh.pub/dns-query
  - https://223.5.5.5/dns-query
  fallback:
  - https://dns.cloudflare.com/dns-query
  - https://public.dns.iij.jp/dns-query
  - https://jp.tiar.app/dns-query
  - https://jp.tiarap.org/dns-query
```

这两个都是用 meta 内核，DNS 解析的过程还不一样吗？为什么一个能解析到一个不能解析到？

最后对openclash的解决方法是，照抄了机场给的配置里的 DNS，多加了几条fallback，包括
```
https://doh.dns.sb/dns-query
https://dns.cloudflare.com/dns-query
tls://8.8.4.4:853
```
然后就解决了，但解决的也莫名其妙的……

另，相同问题还出现在 clash meta for android alpha，由于是没有更改任何配置的情况下出现的问题，可能是外部环境发生了变化导致的，但为什么在同样的环境下 cfw 的表现不同呢？
