### DISCUSSION TITLE
电脑浏览器反复ERR_CONNECTION_REFUSED

### DISCUSSION THREAD

**Discussion by YUUUCC** [vernesong/OpenClash#4231] [Q&A]
设备R4S，电脑刚升级24H2。
之前是前置mosdns，后面跟着openclash，突然打开网页巨慢，卸载mosdns后网络彻底不行了，然后重装了最新的istoreos+openclash，但是电脑经常提示
```
无法访问此网站
XXXXXX 拒绝了我们的连接请求。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
ERR_CONNECTION_REFUSED
```
国内国外都有这种情况，甚至是刚打开网页没多久，刷新一下也有可能会出现，浏览器报错的时候clash的日志里不会出现相关内容。这种时候https://browserleaks.com/dns 打开也看不到任何一个DNS。但是手机上一切正常。
电脑上一般过几分钟就可以打开了。而且国内网站出问题的时候，在电脑上ping相关网址也ping不通，ping1.1.1.1倒是可以，所以怀疑是dns的问题。但是关掉openclash，国内网站就不会出现这种情况。
电脑端wifi适配器关掉ipv6也可恢复正常，但是我已经在软路由上关闭ipv6了（参考https://www.cnblogs.com/NueXini/p/15707858.html）

openclash配置如下：（相关规则来自https://github.com/Loyalsoldier/clash-rules）
```
---
proxies:

proxy-groups:

rules:
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- RULE-SET,icloud,DIRECT
- RULE-SET,apple,DIRECT
- RULE-SET,applications,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- RULE-SET,private,DIRECT
- RULE-SET,tld-not-cn,FAST
- RULE-SET,reject,REJECT
- RULE-SET,gfw,FAST
- MATCH,DIRECT

rule-providers:

dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  fake-ip-filter-mode: blacklist
  nameserver:
  - tls://8.8.8.8:853
  - tls://8.8.4.4:853
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://9.9.9.9/dns-query
  - https://149.112.112.112/dns-query
  - https://45.11.45.11/dns-query
  - https://208.67.222.222/dns-query
  - https://101.101.101.101/dns-query
  - https://208.67.220.220/dns-query
  - https://185.222.222.222/dns-query
  nameserver-policy:
    rule-set:icloud,apple:
    - https://223.5.5.5/dns-query
    - https://119.29.29.29/dns-query
    - https://149.112.112.112/dns-query
    - https://101.101.101.101/dns-query
    - https://9.9.9.9/dns-query
    - https://208.67.220.220/dns-query
    - https://185.222.222.222/dns-query
    - https://45.11.45.11/dns-query
    - https://1.12.12.12/dns-query
    - https://120.53.53.53/dns-query
    - https://208.67.222.222/dns-query
    geosite:cn,apple,private:
    - https://223.5.5.5/dns-query
    - https://119.29.29.29/dns-query
    - https://149.112.112.112/dns-query
    - https://101.101.101.101/dns-query
    - https://9.9.9.9/dns-query
    - https://208.67.220.220/dns-query
    - https://185.222.222.222/dns-query
    - https://45.11.45.11/dns-query
    - https://1.12.12.12/dns-query
    - https://120.53.53.53/dns-query
    - https://208.67.222.222/dns-query

  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time-ios.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - "+.qq.com"
  - "+.tencent.com"
  - "+.srv.nintendo.net"
  - "*.n.n.srv.nintendo.net"
  - "+.cdn.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.*.microsoft.com
  - "*.*.xboxlive.com"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - "+.stun.*.*.*.*.*"
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - stun.l.google.com
  - na.b.g-tun.com
  - "+.nflxvideo.net"
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "*.ff14.sdo.com"
  - ff.dorado.sdo.com
  - "*.mcdn.bilivideo.cn"
  - "+.media.dssott.com"
  - shark007.net
  - Mijia Cloud
  - "+.cmbchina.com"
  - "+.cmbimg.com"
  - local.adguard.org
  - "+.sandai.net"
  - "+.n0808.com"
  - "+.uu.163.com"
  - ps.res.netease.com
  - "+.pub.3gppnetwork.org"
  - geosite:category-games

  fallback:
  - 8.8.8.8
  - 8.8.4.4

  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  - 45.11.45.11
  - 9.9.9.9
  - 223.6.6.6
  - 208.67.222.222
  - 185.222.222.222
  - 149.112.112.112
  - 101.101.101.101
  - 208.67.220.220
  fallback-filter:

redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
allow-lan: true
disable-keep-alive: true
external-controller: 0.0.0.0:9090
secret: X
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
ipv6: false
tcp-concurrent: true
sniffer:
  enable: true
  parse-pure-ip: true
tun:
  enable: true
  stack: gvisor
  device: utun
  dns-hijack:
  - tcp://any:53
  gso: true
  gso-max-size: 65536
  auto-route: false
  auto-detect-interface: false
  auto-redirect: false
  strict-route: false
profile:
  store-selected: true
  store-fake-ip: true
authentication:
- X
```

想请教一下这是因为DNS服务商限制了，还是我的电脑、浏览器设置有问题？
