### DISCUSSION TITLE
配置中设置的hosts不起效

### DISCUSSION THREAD

**Discussion by Starseeker-H** [vernesong/OpenClash#4239] [Q&A]
DNS 部分配置如下
```
dns:
  enable: true
  use-hosts: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
  - 202.118.66.6
  - 223.5.5.5
  - 114.114.114.114
  - 119.29.29.29
  - https://doh.pub/dns-query
  - https://223.5.5.5/dns-query
  fallback:
  - https://doh.dns.sb/dns-query
  - https://dns.cloudflare.com/dns-query
  - https://dns.twnic.tw/dns-query
  - https://public.dns.iij.jp/dns-query
  - https://jp.tiar.app/dns-query
  - https://jp.tiarap.org/dns-query
  - tls://8.8.4.4:853
hosts:
  'xz39.xyz': 192.168.1.15
```
但内网设备无法获取到域名对应IP

```
PS C:\WINDOWS\system32> nslookup xz39.xyz 192.168.1.1
服务器:  XZ_Op.lan
Address:  192.168.1.1

*** 没有 xz39.xyz 可以使用的 internal type for both IPv4 and IPv6 Addresses (A+AAAA)记录
```

请问是还有哪里需要更改吗？
