### DISCUSSION TITLE
如何添加内网代理做出站？

### DISCUSSION THREAD

**Discussion by m0e16** [vernesong/OpenClash#4250] [Q&A]
- OpenClash v0.46.050
- Fake-IP：混合模式
- 本地DNS 模式：使用防火墙转发
- 局域网访问控制模式：黑名单模式
- 将该设备Mac添加到不走代理名单

现在在该设备上架设了SOCKS5代理，如何将该SOCKS5代理用作出站？

**Comment by fejeIaqbhbv** [comment]
看不懂你的需求，两种都列了，希望以后再描述清晰些
> 该设备上架设了SOCKS5代理

[pc-socks5-openclash-google](https://wiki.metacubex.one/config/rules/#in-type)
> SOCKS5代理用作出站

[pc-openclash-socks5-google](https://wiki.metacubex.one/config/proxies/socks/)

**Reply by m0e16** [reply]
不好意思，我重新描述一下：我有一台设备，内网IP为192.168.1.14，我在这台设备上架设了SOCKS代理，这台设备我在OpenClash 的`插件设置-黑白名单`设置了不走代理。
现在我想在OpenClash 添加一个proxies：
```
proxies:
- name: "socks"
  type: socks5
  server: 192.168.1.14
  port: 9999
```
然而无法使用。但是内网中的其他设备，电脑手机等，都可以添加192.168.1.14:9999为代理服务器。

**Reply by fejeIaqbhbv** [reply]
再问一下有写rule吗？
`- domain,google,socks`？

黑白名单只管进不管出，所以应该无关

**Reply by m0e16** [reply]
写了，需要代理的域名或者直连的我都试过，都不行。

**Reply by fejeIaqbhbv** [reply]
测了一下，不过我是用的两台openwrt的openclash
```mermaid
flowchart TD
pppoeA<-->192.168.1.1
pppoeB<--192.168.11.1-->A(wan1:192.168.11.1 wan2:192.168.1.131)
192.168.1.1<--192.168.1.131-->A
192.168.1.1<--socks192.168.1.131:7891-->设备A
A<--socks192.168.11.1:7891-->设备B
```
新安装openclash(wan1:192.168.11.1|wan2:192.168.1.131)
模式fakip tun混合
dns劫持 防火墙模式
黑白名单 proxies节点socks的所属ip和mac(192.168.1.1) 黑名单
上传配置文件
```yaml
proxies:
- name: socks
  type: socks5
  server: 192.168.1.1
  port: 7891
  username: Clash
  password: I4BPygAg
rules:
- MATCH,socks
```
没有调整其它功能设置
启动openclash
测试网络畅通
![1](https://github.com/user-attachments/assets/2a25d08e-3c1a-43c2-900b-fe1a40c7a413)

---
你可以看看debug日志有没有什么相关信息
