### ISSUE TITLE
在配置文件订阅类型为V2rayN，不能正确识别伪装域名配置

### ISSUE THREAD

**Issue by wolnlow** [vernesong/OpenClash#102]
在配置文件订阅类型为V2rayN，伪装域名配置不能被正确识别，ws-headers为空

**Comment by vernesong** [comment]
https://fndroid.github.io/api_constructor/
看看在这转的文件有没有问题

**Comment by wolnlow** [comment]
> 
> 
> https://fndroid.github.io/api_constructor/
> 看看在这转的文件有没有问题

订阅链接是V2aryN的，没有转，另外即使用上面链接转也识别不了，再另外即使在服务器节点配置里面修改，把ws-headers填进去，也不行！

**Comment by vernesong** [comment]
在页面上添加会生成{HOST:www.baidu.com}的形式，我这边测试可以正常加到配置文件

**Comment by chenweiyu** [comment]
我遇到一个可能算是相关的问题。订阅链接里的节点信息大概是这样的格式： 
```
Proxy:
- alterId: 1
  cipher: auto
  name: "某某节点"
  network: ws
  port: xxx
  server: xxx.xxx.xxx.xxx
  tls: false
  type: vmess
  uuid: xxxxxxxxxxxxxxxxxxxxxxxxxxx
  ws-headers:
    Host: xxxxx.com
  ws-path: /
- alterId: 1
  cipher: auto
  ...
```
openclash设置直接使用订阅配置，启动openclash的时候错误信息：    
```
time="2020-01-05T11:03:49Z" level=fatal msg="Parse config error: yaml: line 14: did not find expected key"
2020-01-05 19:03:48 OpenClash Can Not Start, Please Check The Error Info And Try Again
```
我用过其他平台的clash，这份订阅的配置应该是正常工作的。找到openclash的配置文件后，发现缩进有问题，变成这样了：
```
Proxy:
- alterId: 1
cipher: auto
name: "某某节点"
network: ws
port: xxx
server: xxx.xxx.xxx.xxx
tls: false
type: vmess
uuid: xxxxxxxxxxxxxxxxxxxxxxxxxxx
ws-headers:
Host: xxxxx.com
ws-path: /
- alterId: 1
cipher: auto
...
```

**Comment by vernesong** [comment]
tab的缩进会删除，识别不了，你看下是不是

> 我遇到一个可能算是相关的问题。订阅链接里的节点信息大概是这样的格式：
> 
> ```
> Proxy:
> - alterId: 1
>   cipher: auto
>   name: "某某节点"
>   network: ws
>   port: xxx
>   server: xxx.xxx.xxx.xxx
>   tls: false
>   type: vmess
>   uuid: xxxxxxxxxxxxxxxxxxxxxxxxxxx
>   ws-headers:
>     Host: xxxxx.com
>   ws-path: /
> - alterId: 1
>   cipher: auto
>   ...
> ```
> 
> openclash设置直接使用订阅配置，启动openclash的时候错误信息：
> 
> ```
> time="2020-01-05T11:03:49Z" level=fatal msg="Parse config error: yaml: line 14: did not find expected key"
> 2020-01-05 19:03:48 OpenClash Can Not Start, Please Check The Error Info And Try Again
> ```
> 
> 我用过其他平台的clash，这份订阅的配置应该是正常工作的。找到openclash的配置文件后，发现缩进有问题，变成这样了：
> 
> ```
> Proxy:
> - alterId: 1
> cipher: auto
> name: "某某节点"
> network: ws
> port: xxx
> server: xxx.xxx.xxx.xxx
> tls: false
> type: vmess
> uuid: xxxxxxxxxxxxxxxxxxxxxxxxxxx
> ws-headers:
> Host: xxxxx.com
> ws-path: /
> - alterId: 1
> cipher: auto
> ...
> ```

**Comment by chenweiyu** [comment]
@vernesong 确认了一下，是两个空格，不是tab。我用的openclash版本v0.35.6-beta，是最新的了

**Comment by vernesong** [comment]
脱敏的配置文件放上来我测试

> @vernesong 确认了一下，是两个空格，不是tab。我用的openclash版本v0.35.6-beta，是最新的了。
> 刚刚尝试了一下直接上传config.yaml文件，但是启动的时候程序会把这个文件修改一遍，又变回没有缩进的了。

**Comment by chenweiyu** [comment]
@vernesong 今晚脱敏配置文件的时候好像发现问题在哪了。
```
Proxy:
- alterId: 1
  cipher: auto
  name: "Test-1"
  network: ws
  port: 123
  server: 123.123.123.123
  tls: false
  type: vmess
  uuid: 0CE0123B-1231-1231-1231-FED123EF123A
  ws-headers:
    Host: www.baidu.com
  ws-path: /
Proxy Group:
- name: PROXY
  proxies:
  - "Test-1"
  type: select
Rule:
- GEOIP,CN,DIRECT
- MATCH,PROXY

dns:
  enable: false
  enhanced-mode: fake-ip
  listen: 0.0.0.0:53
  nameserver:
  - 119.29.29.29
  - 223.5.5.5
external-controller: 127.0.0.1:9090
log-level: info
mode: Rule
port: 7890
socks-port: 7891
```
配置文件里带有dns的话，openclash处理过后缩进就会被破坏掉。把dns删掉就可以正常使用了。
ps: openclash里的全局配置 - DNS设置 - 本地DNS劫持： 启用
自定义上游DNS服务器 启用和禁用都试过，都有问题
