### ISSUE TITLE
没有代理  IPv6 流量

### ISSUE THREAD

**Issue by EkkoG** [vernesong/OpenClash#1078]
经过修改后的配置文件 如下

```yaml
---
external-controller: 0.0.0.0:9090
port: 7890
socks-port: 7891
redir-port: 7892
proxies:
- type: vmess
  cipher: none

rules:

- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- GEOIP,CN,DIRECT
- "MATCH,\U0001F680 Proxy"
dns:
  nameserver:
  - 127.0.0.1:6053
  enable: true
  ipv6: true
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
secret: ''
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
ipv6: true

```

两个 ipv6 选项都打开，上游 DNS 也是支持 IPv6 的，同时会返回 AAAA 记录，如果有的话

观察到的现象是如果走 IPv6 出去，出口 IP 都是我本机的 IP，同一个域名如果走 IPv4，刚是走了代理，出口为代理IP，所以应该是没有代理这部分 IPv6 流量
