### ISSUE TITLE
服务器节点配置的ws-headers问题

### ISSUE THREAD

**Issue by vaakian** [vernesong/OpenClash#1144]
难道ws-headers下的参数，就是作为字符串全部放到Host属性里了吗？
Host应该仅作为ws-headers的一个属性呀，我还想自己添加一些其他属性，供服务器分流。

当然可能是我的姿势不对？

配置：
![image](https://user-images.githubusercontent.com/30516060/103618359-bbeb2200-4f27-11eb-8c2d-1ee26d973472.png)

期望的是：
```yaml
    ws-headers:
      Host: bap.test.dev
      target: 01.HKG.ASIA.NET
```

结果是：
![image](https://user-images.githubusercontent.com/30516060/103618425-db824a80-4f27-11eb-924b-e4fc12c0cf0d.png)
