### ISSUE TITLE
向现有配置文件中追加策略组和外部规则集的操作

### ISSUE THREAD

**Issue by newpoliceman** [vernesong/OpenClash#1327]
需求：
新建Sony策略组，类型select，包含节点Domestic, Proxy
自定义Rule-set，命名为Sony，yaml文件通过http获取，使用策略组Sony。

操作：
服务器&策略组管理-》策略组配置，按上述要求增加策略组Sony
规则集与策略组管理-〉自定义规则集与策略组管理，按上述要求添加规则集Sony

运行结果：
规则集配置被自动添加到运行配置文件中，策略组配置未被自动添加到运行配置文件中，运行失败，报错找不到Proxy【Sony】。

临时解决办法：
更新配置文件订阅后，手动向订阅的配置文件"proxy-groups:"中添加策略组信息：
```
- name: Sony
  type: select
  proxies: 
  - Domestic
  - Proxy
```
即可运行成功。但问题是如果更新了配置文件订阅，需要重新手动添加，如果自定义内容多，操作不便。

请教一下，是我配置策略组的操作有错误吗？
