### ISSUE TITLE
openclash启动不成功

### ISSUE THREAD

**Issue by WULANREN8177** [vernesong/OpenClash#1424]
### 报错日志：
![image](https://user-images.githubusercontent.com/67304509/123547552-d47c1c80-d793-11eb-8ffc-e524f9557255.png)
![WULANREN_2021-06-27_21-11-59](https://user-images.githubusercontent.com/67304509/123547649-2e7ce200-d794-11eb-8640-f46afa206e1e.png)
![WULANREN_2021-06-27_21-12-02](https://user-images.githubusercontent.com/67304509/123547660-3472c300-d794-11eb-9ba0-8703b3f2c658.png)
### 配置文件(节点信息已匿名。并且在cfw上都可以正常上网)
````
port: 7890
socks-port: 7891
allow-lan: false
bind-address: "*"
mode: Rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
hosts: null
dns:
  enable: true
  enhanced-mode: redir-host
  nameserver:
    - 8.8.8.8
    - 114.114.114.114
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 198.18.0.2:53
  auto-route: true
  auto-detect-interface: true
proxies:
  - name: 🇭🇰 HK_CMI
    type: vmess
    server: 111.111.111.111
    port: XXXXX
    uuid: 1111111111111111111111111111111
    alterId: 1
    cipher: none
  - name: 🇸🇬 SG_BGP
    type: vmess
    server: 111.111.111.111
    port: 443
    uuid: 1111111111111111111111111111111
    alterId: 2
    cipher: auto
    tls: true
    network: ws
    ws-path: /SoftDown
    ws-headers:
      Host: 111.111.111.111
  - name: 🇺🇸 CN2-V215-2x-美国-NF
    server: 111.111.111.111
    port: 56298
    type: vmess
    uuid: 11111111111111111111111111111111
    alterId: 2
    cipher: auto
    tls: false
    network: ws
    ws-path: /v2ray
    ws-headers:
      Host: 111.111.111.111
    udp: true
  - name: Raspberry PI Neteasemusic
    type: http
    server: 111.111.111.111
    port: 5200
    _index: 3
proxy-groups:
  - name: 🎵 Neteasemusic
    proxies:
      - Raspberry PI Neteasemusic
    type: select
  - name: 🚀 PROXY
    proxies:
      - 🇭🇰 HK_CMI
      - 🇸🇬 SG_BGP
    type: select
  - name: 👰 DisneyPlus
    proxies:
      - 🇸🇬 SG_BGP
      - 🇭🇰 HK_CMI
    type: select
  - name: 🗺︎ Streaming
    proxies:
      - 🇭🇰 HK_CMI
      - 🇺🇸 CN2-V215-2x-美国-NF
      - DIRECT
    type: select
  - name: 🍀 StreamingSE
    proxies:
      - 🇭🇰 HK_CMI
      - 🇺🇸 CN2-V215-2x-美国-NF
      - DIRECT
    type: select
rule-providers:
  Unbreak:
    type: http
    behavior: classical
    path: ./RuleSet/Unbreak.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Unbreak.yaml
    interval: 86400
  DisneyPlus:
    type: http
    behavior: classical
    path: ./RuleSet/DisneyPlus.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Video/DisneyPlus.yaml
    interval: 86400
  Streaming:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/Streaming.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Streaming.yaml
    interval: 86400
  StreamingSE:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/StreamingSE.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingSE.yaml
    interval: 86400
  Global:
    type: http
    behavior: classical
    path: ./RuleSet/Global.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Global.yaml
    interval: 86400
  China:
    type: http
    behavior: classical
    path: ./RuleSet/China.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml
    interval: 86400
  ChinaIP:
    type: http
    behavior: ipcidr
    path: ./RuleSet/Extra/ChinaIP.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/ChinaIP.yaml
    interval: 86400
rules:
  - DOMAIN-SUFFIX,github.blog,🚀 PROXY
  - DOMAIN-SUFFIX,music.163.com,🎵 Neteasemusic
  - DOMAIN-SUFFIX,music.126.net,🎵 Neteasemusic
  - DOMAIN,mam.netease.com,🎵 Neteasemusic
  - DOMAIN,api.iplay.163.com,🎵 Neteasemusic
  - DOMAIN,luciovilla.com,🚀 PROXY
  - DOMAIN,www.heibaizhibo.com,🚀 PROXY
  - DOMAIN,emojiall.com,🚀 PROXY
  - RULE-SET,Unbreak,DIRECT
  - RULE-SET,DisneyPlus,👰 DisneyPlus
  - RULE-SET,Streaming,🗺︎ Streaming
  - RULE-SET,StreamingSE,🍀 StreamingSE
  - RULE-SET,Global,🚀 PROXY
  - RULE-SET,China,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT
  - IP-CIDR,fe80::/10,DIRECT
  - IP-CIDR,119.28.28.28/32,DIRECT
  - IP-CIDR,182.254.116.0/24,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,DIRECT
````
