### ISSUE TITLE
[功能请求] 添加对IPv6地址的代理服务器的支持

### ISSUE THREAD

**Issue by waynon** [vernesong/OpenClash#1460]
随着运营商对IPv6支持的逐渐改善，IPv6地址的代理服务器已经达到可用状态。并且支持IPv6还有以下好处：
- 在某些情况下，使用IPv6地址的代理服务器甚至比IPv4地址的更快
- 当IPv4地址被墙已后，IPv6地址也可以作为一个很好的替代。

目前server填写IPv6地址会报错 (ip version error)，配置如下：
```
proxies:
  - name: "2001:470:1f05:316::2"
    type: vmess
    server: 2001:470:1f05:316::2
    port: 27399
    uuid: 63299985-190d-4337-a5c4-71b7adbcc0bd
    alterId: 0
    cipher: auto
    udp: false
    skip-cert-verify: false
    tls: false
```
