### ISSUE TITLE
dns 之后存在 cfw-bypass ， 配置文件处理异常导致 openclash 启动会报错

### ISSUE THREAD

**Issue by hitsmaxft** [vernesong/OpenClash#156]
服务提供的托管文件前面的格式是

```
dns:
....

cfw-bypass:
....

Proxy Group:
...

```

每次自动更新之后就会报错yml格式错误

看了下 openclash 的启动代码，启动过程中将配置文件用 sed 切割了，硬编码了配置文件顺序
多出来这个 `cfw-bypass` ，导致文件分段不对，本来在dns部分最后插入 fallback-filter 被插入到 cfw-baypass去了，导致启动报错。

有没有可能改善一下对配置顺序的支持？

我现在是手动改了代码，调整配置文件的时候把 cfw-bypass 段删了，就能正常运行了。

**Comment by vernesong** [comment]
启动时cfw-bypass这一段会被删除，实际上是需要添加fallback-filter时会删除fallback和proxy之间的内容。
你可以提供你的配置，而不是省略的形式
新版没有复现出这个问题

**Comment by hitsmaxft** [comment]
[testcase.zip](https://github.com/vernesong/OpenClash/files/4234076/testcase.zip)


可以重现的最小case， 输出的 DNS_FILE 内容结构是错误的。 

```
  nameserver:
  - 1.2.4.8
  fallback:
  - tls://1.0.0.1:853

cfw-bypass:
  - qq.com
  - taobao.com
  - music.163.com
  - <local>
cfw-latency-timeout: 5000
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
#===================== OpenClash-General-Settings =====================#
```

代码基于master， 关闭 proxy provider mode 和 custom dns 

我的脚本是mac上的， sed 用的是 gnu-sed ， linux环境需要把 gsed 替换成 sed 。
