### ISSUE TITLE
使用 redir-host 时报错无法启动 clash

### ISSUE THREAD

**Issue by jyuny1** [vernesong/OpenClash#183]
**同样设置使用 fake-ip 是没问题的，可正常工作**

日志显示

> time="2020-02-29T05:05:22Z" level=fatal msg="Parse config error: yaml: line 18: did not find expected key"

整体已经升级到最新版
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/94984/75601337-0d02dc00-5af5-11ea-90b1-ced2fd27266a.png">

根据报错的信息看了下第 18 行是 nameserver 那段，不知道是什么问题。求解答
```
redir-port: 7892
port: 7890
socks-port: 7891
mode: Rule
log-level: silent
external-controller: 192.168.50.1:9090
secret: "XXXXX"
allow-lan: true
bind-address: "192.168.50.1"
external-ui: "/usr/share/openclash/dashboard"
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
##Custom DNS##
  nameserver:
  - 223.5.5.5:53
  - 180.76.76.76:53
  fallback:
  - tls://8.8.4.4:853
  - tls://1.0.0.1:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
```

另一个可正常使用的朋友设定
```
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:2083
  enhanced-mode: redir-host
  # fake-ip-range: 198.18.0.1/16
  # fake-ip-filter:
  #   - "*.lan"
  #   - "*.local"
  #   - "*.midway.io"
  nameserver:
  - 223.5.5.5
  - 114.114.114.114
  - 119.28.28.28
  fallback:
  - tls://1.0.0.1:853
  - tls://8.8.4.4:853


  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
```
