### ISSUE TITLE
自定义规则排序错乱的问题

### ISSUE THREAD

**Issue by htfcuddles** [vernesong/OpenClash#1848]
## 描述bug
设置自定义规则后，生成运行配置中是逆序排序的。

## 复现步骤
1. 全局设置-规则设置-设置自定义规则（候补匹配），设置1条脚本和3条规则，例如：
```
script:
  shortcuts:
    shortcut1: xxx
rules:
 - A
 - B
 - C
```

2. 应用配置，下载运行配置，发现生成的规则是倒叙的：
```
script:
  shortcuts:
    shortcut1: xxx
rules:
 - some other rules
 - C
 - B
 - A
```

## 你想要实现的目的
因为第三方规则不满足我的需求，我自己写了很多自定义规则，对其顺序有严格要求。work-around是自己在写规则时脑补逆序一下，十分蛋疼。。。

## 系统相关信息
版本：v0.44.03

## 其他相关信息
出问题的应该是下面这行代码，大神请问reverse有何具体意图吗？不太理解
https://github.com/vernesong/OpenClash/blob/19a10867e09a103068d5ecda381d6cd1e28918df/luci-app-openclash/root/usr/share/openclash/yml_rules_change.sh#L73
