### ISSUE TITLE
启用“自定义规则(访问控制)”后启动报错

### ISSUE THREAD

**Issue by vindia9** [vernesong/OpenClash#189]
### 故障描述：

- 关闭 全局设置-规则设置-自定义规则(访问控制)  时能成功启动服务，但打开这个选项启动就会报错。

### 运行环境 :

已选择编译版本 : linux-amd64
处理器架构（PROC） : x86_64
当前内核版本 : v0.18.0-3-gc4994d6
当前客户端版本 : v0.36.7-beta
运行模式 : Fake-IP（增强）
代理模式 : Rule
DNS设置-高级设置 : 启用
自定义规则 : 停用
Openwrt固件版本 : OpenWrt SNAPSHOT r12314-a422b171ac / LuCI Master git-20.055.55429-c6ce80e
内核版本 : 4.19.106

### 错误日志 :

> time="2020-03-02T04:55:06Z" level=fatal msg="Parse config error: yaml: line 49: could not find expected ':'"
> 2020-03-02 12:55:06 OpenClash Can Not Start, Try Use Backup Rules Start Again
> time="2020-03-02T04:55:10Z" level=info msg="Start initial compatible provider GoProxy"
> time="2020-03-02T04:55:10Z" level=info msg="Start initial compatible provider Domestic"
> 2020-03-02 12:55:06 OpenClash Start Successful With Backup Rules Config, Please Check Or Update Other Rules And Retry
> 2020-03-02 12:55:06 OpenClash Start Successful, Please Note That Network May Abnormal With IPV6's DHCP Server

### 我的配置文件 :

- Server Port Password 部分做过替换，但用替换过的配置文件运行过，出现同样的错误。

```
port: 7890
socks-port: 2347
redir-port: 7892
allow-lan: true
bind-address: "*"
mode: Rule
log-level: warning
external-controller: 0.0.0.0:9090
secret: "123456"
cfw-latency-url: 'http://www.gstatic.com/generate_204'
external-ui: "/usr/share/openclash/dashboard"
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5450
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - 202.96.209.5
  - 202.96.209.133
  fallback:
  - tls://1.0.0.1:853
  - tls://dns.google:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
Proxy:
  - { name: HK1, type: ss, server: hk1.edge.rtim53.com, port: 23122, cipher: chacha20-ietf-poly1305, password: bL1yxdGlqwQ4ZRxv, udp: true }
  - { name: HK2, type: ss, server: hk2.edge.rtim53.com, port: 23122, cipher: chacha20-ietf-poly1305, password: bL1yxdGlqwQ4ZRxv, udp: true }
  - { name: HK3, type: ss, server: hk3.edge.rtim53.com, port: 23122, cipher: chacha20-ietf-poly1305, password: bL1yxdGlqwQ4ZRxv, udp: true }
  - { name: HK4, type: ss, server: hk4.edge.rtim53.com, port: 23122, cipher: chacha20-ietf-poly1305, password: bL1yxdGlqwQ4ZRxv, udp: true }
Proxy Group:
  - { name: GoProxy, type: select, proxies: [HK1, HK2, HK3, HK4] }
  - { name: Domestic, type: select, proxies: [DIRECT, GoProxy] }
Rule:
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,9.9.6.0/22,DIRECT
  - IP-CIDR,9.9.1.0/27,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,17.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - GEOIP,CN,Domestic
  - MATCH,GoProxy
```

### 设置自定义规则（在上方规则设置中启用本功能后生效）

- 这段增加了2行IP-CIDR

```
##- DOMAIN-SUFFIX,google.com,Proxy 匹配域名后缀(交由Proxy代理服务器组)
##- DOMAIN-KEYWORD,google,Proxy 匹配域名关键字(交由Proxy代理服务器组)
##- DOMAIN,google.com,Proxy 匹配域名(交由Proxy代理服务器组)
##- DOMAIN-SUFFIX,ad.com,REJECT 匹配域名后缀(拒绝)
##- IP-CIDR,127.0.0.0/8,DIRECT 匹配数据目标IP(直连)
##- SRC-IP-CIDR,192.168.1.201/32,DIRECT 匹配数据发起IP(直连)
##- DST-PORT,80,DIRECT 匹配数据目标端口(直连)
##- SRC-PORT,7777,DIRECT 匹配数据源端口(直连)

IP-CIDR,2.2.2.6.0/22,DIRECT
IP-CIDR,2.2.2.0/27,DIRECT

##排序在上的规则优先生效,如添加（去除规则前的#号）：
##IP段：192.168.1.2-192.168.1.200 直连
##- SRC-IP-CIDR,192.168.1.2/31,DIRECT
##- SRC-IP-CIDR,192.168.1.4/30,DIRECT
##- SRC-IP-CIDR,192.168.1.8/29,DIRECT
##- SRC-IP-CIDR,192.168.1.16/28,DIRECT
##- SRC-IP-CIDR,192.168.1.32/27,DIRECT
##- SRC-IP-CIDR,192.168.1.64/26,DIRECT
##- SRC-IP-CIDR,192.168.1.128/26,DIRECT
##- SRC-IP-CIDR,192.168.1.192/29,DIRECT
##- SRC-IP-CIDR,192.168.1.200/32,DIRECT

##IP段：192.168.1.202-192.168.1.255 直连
##- SRC-IP-CIDR,192.168.1.202/31,DIRECT
##- SRC-IP-CIDR,192.168.1.204/30,DIRECT
##- SRC-IP-CIDR,192.168.1.208/28,DIRECT
##- SRC-IP-CIDR,192.168.1.224/27,DIRECT

##此时IP为192.168.1.1和192.168.1.201的客户端流量走代理（策略），其余客户端不走代理
##因为Fake-IP模式下，IP地址为192.168.1.1的路由器自身流量可走代理（策略），所以需要排除
##在线IP段转CIDR地址：http://ip2cidr.com
```

### 设置自定义Hosts，仅在Redir-Host模式下生效（不会覆盖配置文件设置）

- 这段没有编辑过

```#  experimental hosts, support wildcard (e.g. *.clash.dev Even *.foo.*.example.com)
#  static domain has a higher priority than wildcard domain (foo.example.com > *.example.com)
#  NOTE: hosts don't work with `fake-ip`

#  '*.clash.dev': 127.0.0.1
#  'alpha.clash.dev': '::1'
```
