### ISSUE TITLE
relay中继节点的域名问题

### ISSUE THREAD

**Issue by aueu** [vernesong/OpenClash#1916]
中继节点出现域名，会出现错误，导致外网断

譬如

```
proxies:
- name: "ss1"
  type: ss
  server: 111.111.111.111
  port: 20202
  cipher: chacha20-ietf
  password: password
- name: "ss2"
  type: ss
  server: ss2.domain.com
  port: 20202
  cipher: chacha20-ietf
  password: password
proxy-groups:
- name: "relay"
  type: relay
  proxies:
    - "ss1"
    - "ss2"
```

出现的log

```
[TCP] dial Proxy (match RuleSet/telegram) to 149.154.175.53:443 error: ParseAddr(\"ss2.domain.com\"): unexpected character (at \"ss2.domain.com\")"
```

改成ip后，恢复正常
