### ISSUE TITLE
Openclash 直连 DNS 解析出错

### ISSUE THREAD

**Issue by henry-tujia** [vernesong/OpenClash#1943]
### 问题复现：
打开OpenClash后，手机打开虎扑，发现无法正常播放视频，但是其余页面非常流畅（图片等无问题）；另外，此时手机进行IPV6 test发现只有国内的IPV4，无IPV6

#### 分流规则截图
目前已经证明，虎扑与IPV6 test均走的是直连（direct），因此规则可能没有问题，如下图所示：
![2022-01-12](https://user-images.githubusercontent.com/69064655/148982423-5c128b77-6108-4830-a757-798d17e5df95.png)
![2022-01-12 (1)](https://user-images.githubusercontent.com/69064655/148982685-052629d8-abb4-4d30-8a30-292762de47c8.png)

#### clash 设置截图

![image](https://user-images.githubusercontent.com/69064655/148983091-79f4cdfc-ada2-4b02-96a9-5415a5f05563.png)
![image](https://user-images.githubusercontent.com/69064655/148983231-e09364c0-72f0-4999-9835-bf5c7c90f35b.png)

#### 规则文件

篇幅缘故，已删除服务器与规则部分

```
---
port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090


dns:
  nameserver:
  - 124.16.97.254
  - "[fe80::7625:8aff:fe0e:b296]:53"
  - dhcp://"eth1"
  - 114.114.114.114
  - 119.29.29.29
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://dns.cloudflare.com/dns-query
  - https://public.dns.iij.jp/dns-query
  - https://jp.tiar.app/dns-query
  - https://jp.tiarap.org/dns-query
  - tls://dot.tiar.app
  enable: true
  ipv6: true
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  default-nameserver:
  - 124.16.97.254
  - "[fe80::7625:8aff:fe0e:b296]:53"
  - 114.114.114.114
  - 119.29.29.29
redir-port: 7892
tproxy-port: 7895
mixed-port: 7893
secret: ''
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
ipv6: false
profile:
  store-selected: true
  store-fake-ip: true
```

### 推测原因

因终端重连网络后可以正常使用（有一定间歇性），因此推测可能是DNS解析问题
