### ISSUE TITLE
[Bug] Duplicated and not supposed to "Proxy" inside Proxy Groups after using "Read Config"

### ISSUE THREAD

**Issue by djoeni** [vernesong/OpenClash#1983]
Here is the example config:
```
proxy-groups:
- name: PROXY
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - LB_Server1
  - LB_Server2
  - LB_Server3
  - Server1
  - Server2
  - Server3
  - Backup_Server1
  - Backup_Server2
  - Backup_Server3
- name: LB_Server1
  type: load-balance
  strategy: round-robin
  disable-udp: false
  proxies:
  - Server1
  - Backup_Server1
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: LB_Server2
  type: load-balance
  strategy: round-robin
  disable-udp: false
  proxies:
  - Server2
  - Backup_Server2
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: LB_Server3
  type: load-balance
  strategy: round-robin
  disable-udp: false
  proxies:
  - Server3
  - Backup_Server3
  url: http://www.gstatic.com/generate_204
  interval: '300'
```

After "Read Config" on tab Servers and Group there is not supposed value inside all Proxy Groups

- inside main group
![bug1](https://user-images.githubusercontent.com/20867437/150659216-051dbfdf-b779-4327-ae5c-1d5c68f7a7d1.png)

- inside each load balance group
![bug2](https://user-images.githubusercontent.com/20867437/150659242-e3301093-001a-4191-9a96-10b9f3c018df.png)

[Optional] regarding vmess old ws format if inside configuration it will automatically parsing into new format but not when inside proxy-provider

thanks
