### ISSUE TITLE
服务器节点配置中wmess信息生成有误

### ISSUE THREAD

**Issue by moezhang** [vernesong/OpenClash#20]
加密方式生成到了tls里
忽略许可验证（skip-cert-verify）没有生成
ws-Path会在前面多生成一个/
添加策略组会生成到dns那

**Comment by vernesong** [comment]
请提供你填写的节点信息示例方便测试

**Comment by moezhang** [comment]
![192 168 1 3_cgi-bin_luci_admin_services_openclash_servers-config_cfg074a8f](https://user-images.githubusercontent.com/37443741/64530623-2e51ef00-d340-11e9-9fdd-b1fb90f04071.png)
![批注 2019-09-09 201612](https://user-images.githubusercontent.com/37443741/64530014-bd5e0780-d33e-11e9-88c4-3b73ecf5d325.png)
生成的配置
```yaml
redir-port: 7892
port: 7890
socks-port: 7891
mode: Rule
log-level: silent
external-controller: 0.0.0.0:9090
secret: "123456"
allow-lan: true
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
dns:测试1
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  nameserver:
  - 114.114.114.114
  - tls://8.8.8.8:853
#===================== OpenClash-General-Settings =====================#
Proxy:
- { name: "test", type: vmess, server: 123.123.123.123, port: 443, uuid: a4510e7e-53bf-47af-ad02-9cc911a17efe, alterId: 16, cipher: aes-128-gcm, skip-cert-verify: falsews-path: //BDjIzdqw/, ws-headers: { Host: baidu.com }, tls: aes-128-gcm }
Proxy Group:
- name: 测试1
  type: select
  proxies:
  - "test"
- name: 测试2
  type: select
  proxies:
  - "test"
Rule:

```
