### ISSUE TITLE
Redir-Host 无法解析DNS 但是 Fake-IP可以

### ISSUE THREAD

**Issue by UchihaYuki** [vernesong/OpenClash#2004]
## 问题描述
使用Redir-Host，浏览器无法打开www.tiktok.com，但是切换到Fake-IP就可以了。

## 我的部分配置简化如下
```
proxy-groups:
  - name: "pc"
    type: "select"
    proxies:
      - us # vmess ws+tls+udp

rules:
  - SRC-IP-CIDR,192.168.31.122/32,pc # pc
```
## 我在路由器上
```
root@router:~# nslookup www.tiktok.com
Server:         127.0.0.1
Address:        127.0.0.1#53

*** Can't find www.tiktok.com: No answer
*** Can't find www.tiktok.com: No answer
```
## 我在pc上
```
>nslookup www.tiktok.com
Server:  router.lan   
Address:  192.168.31.1

DNS request timed out.
    timeout was 2 seconds.
*** Request to router.lan timed-out
```
但是我在proxy server (us)上是可以解析的，从Redir-Host直接切换到Face-IP也是可以访问的，未曾改动过openclash的默认DNS设置。
