### ISSUE TITLE
Rule Provider 规则集备份问题

### ISSUE THREAD

**Issue by leeharuhiofcn** [vernesong/OpenClash#2065]
### 操作流程和遇到的问题
通过【配置文件管理】中的【备份】按钮进行备份，生成了备份文件【~OpenClash.tar.gz】
备份文件虽有rule_provider文件夹以及所用的规则集，但通过该备份文件进行恢复后
【规则集与策略组的管理】中【自定义规则集与策略组管理】的项目并没有得到恢复。需要手动再次填写！

### 提问
这是否意味着无法通过以上方法进行备份?
如果有其他备份方法，请指导！非常感谢！

### 补充
我的理解上，Rule Provider 应该有对应的yaml文件来记叙并保存，类似以下。但就是在备份文件里找不到。
```
rule-providers:
  Google:
      type: http
      behavior: domain
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt
      interval: 86400
```
