### ISSUE TITLE
面板显示守护程序未运行，后台有很多个watchdog进程

### ISSUE THREAD

**Issue by fjjking** [vernesong/OpenClash#2069]
每次开启clash都会多出一个 watchdog，这种情况正常吗？
关闭clash后dns不会恢复到开启之前的样子，并且不去后台杀掉所有watchdog进程就没法改DNS。
是我哪里设置有问题吗？虽然正常使用不影响但小毛病挺烦人的
```
OpenClash 调试日志

生成时间: 2022-02-18 01:59:22
插件版本: v0.44.26-beta
隐私提示: 上传此日志前请注意检查、屏蔽公网IP、节点、密码等相关敏感信息


#===================== 系统信息 =====================#

主机型号: Micro-Star International Co., Ltd. MS-7B89
固件版本: OpenWrt 21.02.1 r16325-88151b8303
LuCI版本: git-20.074.84698-ead5e81
内核版本: 5.4.154
处理器架构: x86_64

#此项有值时,如不使用IPv6,建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: 

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

#===================== 依赖检查 =====================#

dnsmasq-full: 已安装
coreutils: 已安装
coreutils-nohup: 已安装
bash: 已安装
curl: 已安装
ca-certificates: 已安装
ipset: 已安装
ip-full: 已安装
iptables-mod-tproxy: 已安装
kmod-ipt-tproxy: 已安装
iptables-mod-extra: 已安装
kmod-ipt-extra: 已安装
libcap: 已安装
libcap-bin: 已安装
ruby: 已安装
ruby-yaml: 已安装
ruby-psych: 已安装
ruby-pstore: 已安装
ruby-dbm: 已安装
kmod-tun(TUN模式): 已安装
luci-compat(Luci-19.07): 已安装

#===================== 内核检查 =====================#

运行状态: 运行中
进程pid: 11241
运行权限: 11241: cap_dac_override,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_resource=eip
运行用户: nobody
已选择的架构: linux-amd64

#下方无法显示内核版本号时请确认您的内核版本是否正确或者有无权限
Tun内核版本: 2022.01.27
Tun内核文件: 存在
Tun内核运行权限: 正常

Dev内核版本: v1.9.0-7-gb1a639f
Dev内核文件: 存在
Dev内核运行权限: 正常

#===================== 插件设置 =====================#

当前配置文件: /etc/openclash/config/config.yaml
启动配置文件: /etc/openclash/config.yaml
运行模式: fake-ip-mix
默认代理模式: script
UDP流量转发(tproxy): 停用
DNS劫持: 启用
自定义DNS: 启用
IPV6代理: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 停用
仅允许内网: 启用
仅代理命中规则流量: 停用
仅允许常用端口流量: 停用
绕过中国大陆IP: 停用
DNS远程解析: 停用

#启动异常时建议关闭此项后重试
混合节点: 停用
保留配置: 启用

#启动异常时建议关闭此项后重试
第三方规则: 停用

#===================== 配置文件 =====================#

port: 10810
socks-port: 10809
allow-lan: true
mode: script
log-level: info
external-controller: 192.168.0.1:9090
proxy-groups:
- name: Currency
  type: select
  disable-udp: false
  proxies:
  - Vmess
  - SSR
  - Unclassified
- name: Vmess
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - AIA+IPLC|香港01|3x
  - AIA+IPLC|香港02|3x
  - AIA+IPLC|香港03|3x
  - AIA+IPLC|香港04|3x
  - AIA+IPLC|香港05|3x
  - AIA+IPLC|香港01(原生)|3x
  - AIA+IPLC|香港02(原生)|3x
  - AIA+IPLC|香港03(原生)|3x
  - AIA+IPLC|香港04(原生)|3x
  - AIA+IPLC|香港05(原生)|3x
  - AIA+IPLC|新加坡01(原生)|3x
  - AIA+IPLC|新加坡02(原生)|3x
  - AIA+IPLC|新加坡03(原生)|3x
  - AIA+IPLC|台湾01(原生)|3x
  - AIA+IPLC|台湾02(原生)|3x
  - AIA+IPLC|台湾03(原生)|3x
  - AIA+IPLC|台湾04(原生)|3x
  - AIA+IPLC|台湾05(原生)|3x
  - AIA+IPLC|台湾06(原生)|3x
  - AIA+IPLC|台湾07(原生)|3x
  - AIA+IPLC|台湾08(原生)|3x
  - AIA+IPLC|台湾09(原生)|3x
  - AIA+IPLC|台湾10(原生)|3x
  - AIA+IPLC|日本01(原生)|3x
  - AIA+IPLC|日本02(原生)|3x
  - AIA+IPLC|日本03(原生)|3x
  - AIA+IPLC|日本04(原生)|3x
  - AIA+IPLC|日本05(原生)|3x
  - AIA+IPLC|美国01(原生)|3x
  - AIA+IPLC|美国02(原生)|3x
  - AIA+IPLC|美国03(原生)|3x
  - AIA+IPLC|美国04(原生)|3x
  - AIA+IPLC|美国05(原生)|3x
  - iplc|广港01|1.5x
  - iplc|广港02|1.5x
  - iplc|广港03|1.5x
  - iplc|广港04|1.5x
  - iplc|广港05|1.5x
  - iplc|广港-原生01|1.5x
  - iplc|广港-原生02|1.5x
  - iplc|广港-原生03|1.5x
  - iplc|广港-原生04|1.5x
  - iplc|广港-原生05|1.5x
  - iplc|广新01|1.5x
  - iplc|广新02|1.5x
  - iplc|广新-原生01|1.5x
  - iplc|广新-原生02|1.5x
  - iplc|广新-原生03|1.5x
  - iplc|广台-原生01|1.5x
  - iplc|广台-原生02|1.5x
  - iplc|广台-原生03|1.5x
  - iplc|广台-原生04|1.5x
  - iplc|广台-原生05|1.5x
  - iplc|广台-原生06|1.5x
  - iplc|广台-原生07|1.5x
  - iplc|广台-原生08|1.5x
  - iplc|广台-原生09|1.5x
  - iplc|广台-原生10|1.5x
  - iplc|广日01|1.5x
  - iplc|广日02|1.5x
  - iplc|广日-原生01|1.5x
  - iplc|广日-原生02|1.5x
  - iplc|广日-原生03|1.5x
  - iplc|广日-原生04|1.5x
  - iplc|广日-原生05|1.5x
  - iplc|广美-原生01|1.5x
  - iplc|广美-原生02|1.5x
  - iplc|广美-原生03|1.5x
  - iplc|广美-原生04|1.5x
  - iplc|广美-原生05|1.5x
  - 中转|香港01
  - 中转|香港02
  - 中转|香港03
  - 中转|香港04
  - 中转|香港05
  - 中转|香港-原生01
  - 中转|香港-原生02
  - 中转|香港-原生03
  - 中转|香港-原生04
  - 中转|香港-原生05
  - 中转|台湾-原生01
  - 中转|台湾-原生02
  - 中转|台湾-原生03
  - 中转|台湾-原生04
  - 中转|台湾-原生05
  - 中转|台湾-原生06
  - 中转|台湾-原生07
  - 中转|台湾-原生08
  - 中转|台湾-原生09
  - 中转|台湾-原生10
  - 中转|新加坡01
  - 中转|新加坡02
  - 中转|新加坡03
  - 中转|日本01
  - 中转|日本02
  - 中转|日本03
  - 中转|日本04
  - 中转|日本05
  - 中转|韩国01
  - 中转|韩国02
  - 中转|韩国03
  - 中转|美国01
  - 中转|美国02
  - 中转|美国03
  - 中转|美国04
  - 中转|美国05
  - 中转|加拿大01
  - Anycast|香港
  - Anycast|新加坡
  - Anycast|日本
  - Anycast|台湾
  - Anycast|泰国
  - Anycast|美国
  - Anycast|英国
  - Anycast|德国
  - Anycast|加拿大
  - Anycast|韩国
  - Anycast|俄罗斯
  - Anycast|荷兰
  - Anycast|印度
  - Anycast|法国
  - Anycast|阿根廷
  - Anycast|巴西
  - Anycast|土耳其
  - Anycast|澳大利亚
  - 福利|新加坡|0.1x|限速10Mbps
  - 福利|香港01|0.1x|限速10Mbps
  - 福利|日本|0.1x|限速10Mbps
  - 福利|美国|0.1x|限速10Mbps
  - 下载专用|0.8x|支持大流量
- name: SSR
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - BGP*台湾台南
  - BGP*日本东京
  - BGP*日本大阪
  - BGP*狮城DC*
  - BGP*狮城EQ*
  - BGP*美国
  - BGP*韩国
  - BGP*香港上环
  - BGP*香港中环
  - BGP*香港九龙
  - DRL*台湾 00  [0.8]
  - DRL*台湾 01 [0.8]
  - DRL*台湾 02 [0.8]
  - DRL*台湾 03 [0.8]
  - DRL*台湾 04 [0.8]
  - DRL*台湾 05 [0.8]
  - DRL*台湾 06 [0.8]
  - DRL*德国
  - DRL*日本东京 00
  - DRL*日本东京 01
  - DRL*日本东京 02
  - DRL*日本东京 03
  - DRL*日本东京 04
  - DRL*日本横滨 [1.5]
  - DRL*日本石狩 [0.8]
  - DRL*日本福岛P*
  - DRL*澳门 01 [1.5]
  - DRL*澳门 02 [1.5]
  - DRL*狮城 00
  - DRL*狮城 01
  - DRL*狮城 02
  - DRL*狮城 03* [1.2]
  - DRL*狮城 04* [1.2]
  - DRL*美国 00
  - DRL*美国 01
  - DRL*美国 02*
  - DRL*美国 03*
  - DRL*美国 04*
  - DRL*越南
  - DRL*韩国 00
  - DRL*韩国 01
  - DRL*香港中环 00
  - DRL*香港中环 01
  - DRL*香港中环 02
  - DRL*香港中环 03
  - DRL*香港九龙 00
  - DRL*香港九龙 02
  - DRL*香港九龙 03
  - DRL*香港御坂P*
  - DRL*香港柴湾 [1.5]
  - DRL*马来西亚01
  - DRL*马来西亚02
  - SP*以色列
  - SP*俄罗斯 [0.5]
  - SP*冰岛
  - SP*加拿大
  - SP*印尼
  - SP*印度
  - SP*土耳其 [3]
  - SP*巴基斯坦V4 [10]
  - SP*巴西 [3]
  - SP*挪威
  - SP*沙特阿拉伯
  - SP*法国
  - SP*泰国
  - SP*澳大利亚
  - SP*瑞士
  - SP*英国伦敦
  - SP*英国伯劳
  - SP*荷兰
  - SP*菲律宾
  - SP*西班牙
  - SP*阿根廷 [3]
- name: Unclassified
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - DRL*韩国5G [0.6]
- name: Socks5
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - Vmess
  - SSR
  - Unclassified
- name: Http
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - Vmess
  - SSR
  - Unclassified
- name: 微软服务
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - Vmess
  - SSR
  - Unclassified
- name: Steam
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - Vmess
  - SSR
  - Unclassified
- name: Other
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - Vmess
  - SSR
  - Unclassified
  - BGP*台湾台南
  - BGP*日本东京
  - BGP*日本大阪
  - BGP*狮城DC*
  - BGP*狮城EQ*
  - BGP*美国
  - BGP*韩国
  - BGP*香港上环
  - BGP*香港中环
  - BGP*香港九龙
- name: Netflix
  type: select
  disable-udp: false
  proxies:
  - Netflix-香港
  - Netflix-台湾
  - Netflix-日本
  - Netflix-新加坡
  - Vmess
  - SSR
  - Unclassified
- name: Netflix-香港
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - BGP*香港上环
  - BGP*香港中环
  - BGP*香港九龙
  - DRL*香港中环 00
  - DRL*香港中环 01
  - DRL*香港中环 02
  - DRL*香港中环 03
  - DRL*香港九龙 00
  - DRL*香港九龙 02
  - DRL*香港九龙 03
  - DRL*香港御坂P*
  - DRL*香港柴湾 [1.5]
- name: Netflix-台湾
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - BGP*台湾台南
  - DRL*台湾 00  [0.8]
  - DRL*台湾 01 [0.8]
  - DRL*台湾 02 [0.8]
  - DRL*台湾 03 [0.8]
  - DRL*台湾 04 [0.8]
  - DRL*台湾 05 [0.8]
  - DRL*台湾 06 [0.8]
- name: Netflix-日本
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - BGP*日本东京
  - BGP*日本大阪
  - DRL*日本东京 00
  - DRL*日本东京 01
  - DRL*日本东京 02
  - DRL*日本东京 03
  - DRL*日本东京 04
  - DRL*日本横滨 [1.5]
  - DRL*日本石狩 [0.8]
  - DRL*日本福岛P*
- name: Netflix-新加坡
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - BGP*狮城DC*
  - BGP*狮城EQ*
  - DRL*狮城 00
  - DRL*狮城 01
  - DRL*狮城 02
  - DRL*狮城 03* [1.2]
  - DRL*狮城 04* [1.2]
rules:
- IP-CIDR,192.168.0.82/32,DIRECT
script:
  code: |-
    def main(ctx, metadata):
      if metadata["type"] == "Socks5":
        return "Socks5"
      if metadata["type"] == "HTTP Connect":
        return "Http"
      if ctx.rule_providers["Other"].match(metadata):
        return "Other"
      if ctx.rule_providers["微软服务"].match(metadata):
        return "微软服务"
      if ctx.rule_providers["Steam"].match(metadata):
        return "Steam"
      if ctx.rule_providers["Netflix"].match(metadata) or ctx.rule_providers["Netflix(By lhie1)"].match(metadata):
        return "Netflix"
      list = ['AppStore','AppStoreConnect','Apple','国内域名','国内IP','放行规则-ConnersHua','放行规则-ACL4SSR','放行规则-ConnersHua','custom']
      for name in list:
        if ctx.rule_providers[name].match(metadata):
          return "DIRECT"
      return "Currency"
rule-providers:
  AppStore:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/AppStore.yaml"
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Extra/Apple/AppStore.yaml
    interval: 86400
  AppStoreConnect:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/AppStoreConnect.yaml"
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Extra/Apple/AppStoreConnect.yaml
    interval: 86400
  Apple:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Apple-lhie1.yaml"
    url: https://cdn.jsdelivr.net/gh/dler-io/Rules@master/Clash/Provider/Apple.yaml
    interval: 86400
  国内域名:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/China.yaml"
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/China.yaml
    interval: 86400
  国内IP:
    type: http
    behavior: ipcidr
    path: "/etc/openclash/rule_provider/ChinaIP.yaml"
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Extra/ChinaIP.yaml
    interval: 86400
  微软服务:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Microsoft.yaml"
    url: https://cdn.jsdelivr.net/gh/dler-io/Rules@master/Clash/Provider/Microsoft.yaml
    interval: 86400
  Netflix(By lhie1):
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Netflix-lhie1.yaml"
    url: https://cdn.jsdelivr.net/gh/dler-io/Rules@master/Clash/Provider/Media/Netflix.yaml
    interval: 86400
  Netflix:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Netflix.yaml"
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/StreamingMedia/Video/Netflix.yaml
    interval: 86400
  放行规则-lhie1:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Special.yaml"
    url: https://cdn.jsdelivr.net/gh/dler-io/Rules@master/Clash/Provider/Special.yaml
    interval: 86400
  放行规则-ACL4SSR:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/UnBan.yaml"
    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/UnBan.yaml
    interval: 86400
  放行规则-ConnersHua:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Unbreak.yaml"
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Unbreak.yaml
    interval: 86400
  Steam:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Steam-ACL4SSR.yaml"
    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/Steam.yaml
    interval: 86400
  custom:
    type: file
    behavior: classical
    path: "/etc/openclash/rule_provider/custom.yaml"
  Other:
    type: file
    behavior: classical
    path: "/etc/openclash/rule_provider/Other.yaml"
dns:
  nameserver:
  - 119.29.29.29
  - 223.5.5.5
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - msftconnecttest.com
  - msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - "+.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - stun.l.google.com
  - "+.nflxvideo.net"
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "*.ff14.sdo.com"
  - ff.dorado.sdo.com
  - "*.mcdn.bilivideo.cn"
  - "+.media.dssott.com"
  default-nameserver:
  - 119.29.29.29
  - 223.5.5.5
redir-port: 7892
tproxy-port: 7895
mixed-port: 10808
bind-address: 192.168.0.1
external-ui: "/usr/share/openclash/dashboard"
ipv6: false
tun:
  enable: true
  stack: system
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
profile:
  store-selected: true
  store-fake-ip: false
interface-name: pppoe-wan

```
