### ISSUE TITLE
OpenClash使用redir-host混合模式，已开启udp转发，无法进入Apex legends服务器

### ISSUE THREAD

**Issue by mrrockist** [vernesong/OpenClash#2113]
在WIndows平台上使用netch通过游戏测试，节点可以转发udp。但是使用openclash转发的时候出现登入界面所有服务器延迟均为一个数值的情况，只能进入到游戏大厅，进入靶场或者游戏服务器之后出现短暂黑屏返回到主菜单界面。
![image](https://user-images.githubusercontent.com/63147162/156490333-a46f2dd3-c8a8-4bca-9faf-4c4a9b838a8e.png)
之后再次点击进入游戏则无法进入大厅，需要在面板里手动将之前连接的服务器ip断开才能进入。

同时发现所选数据中心和实际匹配服务器地理位置有错误的情况（例如我所选香港服务器，但实际会匹配到法国或者美国服务器）

**Comment by vernesong** [comment]
#1997

**Comment by mrrockist** [comment]
> #1997

已经看过了，但由于路由装了docker似乎用不了兼容模式的情况开udp转发（现在已经卸载了docker也似乎无法使用）

**Comment by vernesong** [comment]
那就用TUN
```
script:
  shortcuts:
    game: network == 'udp' and dst_port not in [21, 22, 23, 53, 80, 123, 143, 194, 443, 465, 587, 853, 993, 995, 998, 2052, 2053, 2082, 2083, 2086, 2095, 2096, 5222, 5228, 5229, 5230, 8080, 8443, 8880, 8888, 8889]

rules:
  - SCRIPT,game,Game-group-name
```
