### ISSUE TITLE
tracing exporter API支持

### ISSUE THREAD

**Issue by xiazeyu** [vernesong/OpenClash#2154]
希望能够增加开关，在生成的配置文件后增加以下代码段，支持tracing exporter API.

```yaml
profile:
  # open tracing exporter API
  tracing: true
```

https://github.com/Dreamacro/clash-tracing/issues/7#issuecomment-814727819
