### ISSUE TITLE
internet time restrictions

### ISSUE THREAD

**Issue by malikshi** [vernesong/OpenClash#2162]
I intended to apply time restriction for a family member with this guide https://openwrt.org/docs/guide-user/firewall/fw3_configurations/fw3_parent_controls but it seems not works along Open clash

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/159128761-8783e6c8-0a7d-40b4-a9b8-85c4f4024370.png)
![image](https://user-images.githubusercontent.com/42875168/159128808-344a3c28-9188-4ce8-954e-46d7c61eeac2.png)

**Comment by malikshi** [comment]
How do limit access 22.00 until 07.00?

**Comment by vernesong** [comment]
![image](https://user-images.githubusercontent.com/42875168/159129471-70bb5687-a18c-4ddc-a94b-2b14ba73f669.png)
transform timezone on your own

**Comment by malikshi** [comment]
> ![image](https://user-images.githubusercontent.com/42875168/159129471-70bb5687-a18c-4ddc-a94b-2b14ba73f669.png) transform timezone on your own

Thank you very much. I will test it

**Comment by malikshi** [comment]
not working? my timezone for UTC +7
```yaml
script:
  shortcuts:
    limit-child: in_cidr(src_ip,'192.168.1.116/32') and (time.now().hour > 14 and time.now().hour < 1)
    limit-brother: in_cidr(src_ip,'192.168.1.111/32') and (time.now().hour > 17 and time.now().hour < 21)
    limit-sister: in_cidr(src_ip,'192.168.1.183/32') and (time.now().hour > 15 and time.now().hour < 20)

rules:
- SCRIPT,limit-child,REJECT
- SCRIPT,limit-sister,REJECT
- SCRIPT,limit-brother,REJECT
```
