### ISSUE TITLE
DNS常年污染

### ISSUE THREAD

**Issue by UchihaYuki** [vernesong/OpenClash#2168]
这个问题困扰我很多年了，之前也在openclash问过，依然没有得到解决，每次遇到的时候我就等一段时间就好了，最近发生的越发频繁，这次想一次性给它解决了。

我觉得应该是遇到了dns污染，判定方法：
1.在浏览器输入example.com，无法访问
2.在hosts文件直接写入example.com的ip地址，就可以访问了

fake-ip和redir-host均存在此问题,远程域名解析开启与否均存在此问题

我的rule规则可以算是全局代理：
```yaml
rules:
  - SRC-IP-CIDR,192.168.31.122/32,pc # pc （pc是一个proxy-group，可以直接选择一个代理节点）
```

因为全局代理，会把域名发送到代理进行重新解析，于是我判定，应该是代理节点在做dns的时候被污染导致，有些节点是机场的我无法测试（但是同机场的人说他们没有这个问题），而我自己的节点，我直接nslookup example.com也是正确的。

虽然全局代理应该和dns的配置无关，但是如下为我的配置：
```yaml
dns:
  nameserver:
  - 100.102.48.1 (不是我写的，应该是openclash加的)
  - dhcp://"pppoe-wan" (不是我写的，应该是openclash加的)
  - tls://1.1.1.1
  - tls://208.67.222.222
  - tls://8.8.8.8
  fallback:
  - tls://1.0.0.1
  - tls://208.67.220.220
  - tls://8.8.4.4
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
  default-nameserver:
  - 100.102.48.1 (不是我写的，应该是openclash加的)
```

谢谢各位了。
