### ISSUE TITLE
static hosts doesn't work

### ISSUE THREAD

**Issue by UchihaYuki** [vernesong/OpenClash#2179]
以下为OpenClash修改后用于启动的配置文件部分内容：
```
hosts:
  example.com: 192.168.31.10
dns:
  use-hosts: true
  nameserver:
  - 100.102.32.1
  - dhcp://"pppoe-wan"
  - https://xxx/getnsrecord
  fallback:
  - https://xxx/getnsrecord
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  listen: 127.0.0.1:7874
  default-nameserver:
  - 114.114.114.114
  - 114.114.115.115
  - 100.102.32.1
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - "+.*"
```
when I run `nslookup example.com`, I got following error:
```

Server:  router.lan
Address:  192.168.31.1

*** No internal type for both IPv4 and IPv6 Addresses (A+AAAA) records available for example.com
```
我的clash config.yaml其实和运行时候差的挺大的：
```
dns:
  use-hosts: true
  nameserver:  
    - 114.114.114.114 # 这个被删了
    - 114.114.115.115 # 这个被删了
  fallback:
    - https://xxx/getnsrecord #这个被加到了nameserver
  enable: true
  ipv6: false
  enhanced-mode: redir-host #这个竟然都改了
  listen: 127.0.0.1:7874
  default-nameserver:
    - 114.114.114.114
    - 114.114.115.115
```
