### ISSUE TITLE
双WAN口开启追加上游DNS，只追加最后一个nameserver

### ISSUE THREAD

**Issue by qatang** [vernesong/OpenClash#2241]
软路由eth3口用来pppoe拨号，eth2口用来连接IPTV，都下发了nameserver，openclash运行配置里只显示最后一个IPTV口的nameserver，如何能把两个nameserver都自动加进来？求解

1. 执行 cat /tmp/resolv.conf.d/resolv.conf.auto
```
# Interface wan
nameserver 202.106.46.162
# Interface iptv
nameserver 192.168.100.1
```

3. 执行 cat /etc/openclash/myconfig.yaml
```
dns:
  nameserver:
  - 192.168.100.1 // 只添加了IPTV的nameserver
  - dhcp://"eth2"
  - 114.114.114.114
  - 119.29.29.29
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://dns.cloudflare.com/dns-query
  - "[2001:da8::666]:53"
  - https://public.dns.iij.jp/dns-query
  - https://jp.tiar.app/dns-query
  - https://jp.tiarap.org/dns-query
  - tls://dot.tiar.app
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  fake-ip-filter:
  - "+.*"
  default-nameserver:
  - 192.168.100.1 // 只添加了IPTV的nameserver
  - 114.114.114.114
  - 119.29.29.29
  - "[2001:da8::666]:53"
```

期望结果：
```
dns:
  nameserver:
  - 202.106.46.162 // 两个都自动加入
  - 192.168.100.1 
  - dhcp://"eth2"
  - 114.114.114.114
  - 119.29.29.29
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://dns.cloudflare.com/dns-query
  - "[2001:da8::666]:53"
  - https://public.dns.iij.jp/dns-query
  - https://jp.tiar.app/dns-query
  - https://jp.tiarap.org/dns-query
  - tls://dot.tiar.app
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  fake-ip-filter:
  - "+.*"
  default-nameserver:
  - 202.106.46.162 // 两个都自动加入
  - 192.168.100.1 
  - 114.114.114.114
  - 119.29.29.29
  - "[2001:da8::666]:53"
```
