### ISSUE TITLE
Log中出现大量从OpenWrt不同端口发起的UDP请求后出现socket too many open files错误

### ISSUE THREAD

**Issue by gui-li** [vernesong/OpenClash#227]
OpenWrt的内网ip地址是192.168.1.4，用作旁路由。
OpenClash版本 v0.36.7-beta
OpenWrt版本: v19.07.2
已选择编译版本 linux-amd64
处理器架构（PROC） x86_64
当前内核版本 v0.18.0-14-gb263095
当前客户端版本 v0.36.7-beta

Config 中服务器配置之前部分：
```
port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
redir-port: 7892
secret: "XXX"
external-ui: "/usr/share/openclash/dashboard"
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
##Custom DNS##
  nameserver:
  - 114.114.114.114
  - 119.29.29.29
```
日志片段：
```
time="2020-03-11T14:30:49Z" level=info msg="[UDP] 192.168.1.4:60809 --> 192.168.1.4 match IPCIDR using DIRECT"
time="2020-03-11T14:30:49Z" level=info msg="[UDP] 192.168.1.4:58002 --> 192.168.1.4 match IPCIDR using DIRECT"
time="2020-03-11T14:30:49Z" level=info msg="[UDP] 192.168.1.4:44127 --> 192.168.1.4 match IPCIDR using DIRECT"
time="2020-03-11T14:30:49Z" level=info msg="[UDP] 192.168.1.4:58740 --> 192.168.1.4 match IPCIDR using DIRECT"
time="2020-03-11T14:30:49Z" level=info msg="[UDP] 192.168.1.4:48356 --> 192.168.1.4 match IPCIDR using DIRECT"
time="2020-03-11T14:30:49Z" level=info msg="[UDP] 192.168.1.4:60707 --> 192.168.1.4 match IPCIDR using DIRECT"
time="2020-03-11T14:30:49Z" level=info msg="[UDP] 192.168.1.4:38721 --> 192.168.1.4 match IPCIDR using DIRECT"
time="2020-03-11T14:30:49Z" level=info msg="[UDP] 192.168.1.4:48234 --> 192.168.1.4 match IPCIDR using DIRECT"
time="2020-03-11T14:30:49Z" level=info msg="[UDP] 192.168.1.4:42212 --> 192.168.1.4 match IPCIDR using DIRECT"
time="2020-03-11T14:30:49Z" level=warning msg="[UDP] dial DIRECT error: listen udp :0: socket: too many open files"
time="2020-03-11T14:30:59Z" level=warning msg="dial AsianTV error: dial tcp4 49.7.32.3:80: socket: too many open files"
time="2020-03-11T14:30:59Z" level=warning msg="dial AsianTV error: dial tcp4 49.7.32.3:80: socket: too many open files"
```
