### ISSUE TITLE
TXT记录走openclash dns吗？

### ISSUE THREAD

**Issue by UchihaYuki** [vernesong/OpenClash#2280]
如下是我的OpenClash修改后用于启动的配置文件
```
dns:
  use-hosts: true
  nameserver:
  - https://doh.example.com/getdnsrecord
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  listen: 0.0.0.0:7874
  default-nameserver:
  - 114.114.114.114
  - 114.114.115.115
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - "+.*"
```
当我在pc用
https://doh.example.com/getdnsrecord?type=txt&name=_acme-challenge.dev.blabla.win
时，是可以查询到TXT记录的。
但是当我在pc用：
```
C:\Data\projects\xxx>nslookup -type=TXT _acme-challenge.blabla.win
Server:  router.lan
Address:  192.168.31.1

*** router.lan can't find _acme-challenge.blabla.win: Non-existent domain
```
难道192.168.31.1不是用的https://doh.example.com/getdnsrecord吗?

**Comment by MBRjun** [comment]
Fake-IP模式不会查询TXT记录吧

**Comment by UchihaYuki** [comment]
我网页设置的是Redir-Host来的，不知道为什么运行之后那里会显示fake-ip，我的配置文件也是enhanced-mode: redir-host，但是nslookup回来的真的ip，不是fake的。

**Comment by UchihaYuki** [comment]
上一次，等到第二天就好了，今天又碰到这个问题。求解。

**Comment by malikshi** [comment]
https://github.com/vernesong/OpenClash/issues/2256
I had some problems. Global setting redir-host but final config become fake-ip isn't weird?

**Comment by UchihaYuki** [comment]
@malikshi 你解决了吗？

**Comment by malikshi** [comment]
Config still fake-ip
```yaml
redir-port: 7892
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: info
allow-lan: true
external-controller: 0.0.0.0:9090
secret: '123456'
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  listen: 0.0.0.0:7874
  fake-ip-filter:
  - "+.*"
  fallback-filter:
    geoip: true
    geoip-code: ID
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
    domain:
    - "+.google.com"
    - "+.facebook.com"
    - "+.youtube.com"
    - "+.githubusercontent.com"
    - "+.googlevideo.com"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
```
