### ISSUE TITLE
家中软路由装OPENCLASH ,订阅了3个机场整合

### ISSUE THREAD

**Issue by kevinyang68** [vernesong/OpenClash#2304]
请问如何能让某一个设备固定出国流量走某一个节点，不和家中电脑其他设备通用，且这个设备也可以实现国内和国外自动分开，只是针对国外部分走固定这个节点，而国内还是直连。

**Comment by vernesong** [comment]
```
##tun core
script:
  shortcuts:
    special-oversea: (geoip(resolve_ip(host)) != 'CN' or geoip(dst_ip) != 'CN') and src_ip == '192.168.1.2'
    special-cn: (geoip(resolve_ip(host)) == 'CN' or geoip(dst_ip) == 'CN') and src_ip == '192.168.1.2'
rules:
  - SCRIPT,special-cn,DIRECT
  - SCRIPT,special-oversea,PROXY
 ```
```
##meta core
rules:
  - AND,((SRC-IP-CIDR,192.168.1.2/32),(OR,((GEOIP,cn),(GEOSITE,geolocation-cn)))),DIRECT
  - NOT,(AND,((SRC-IP-CIDR,192.168.1.2/32),(OR,((GEOIP,cn),(GEOSITE,geolocation-cn))))),PROXY
