### ISSUE TITLE
TUN内核，UDP使用TProxy和TUN，测出来NAT类型不同

### ISSUE THREAD

**Issue by returnL** [vernesong/OpenClash#2342]
### 版本及配置信息
OpenClash：v0.45.12-beta
TUN内核：04.17 Premuim
DNS配置：
```yaml
dns:
  enable: true
  listen: 127.0.0.1:8853
  enhanced-mode: fake-ip
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 1.0.0.1
  nameserver:
    - https://dns.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - tls://1.0.0.1
    - https://public.dns.iij.jp/dns-query
    - tls://8.8.4.4
  fake-ip-filter:
    - "+.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - "time.*.com"
    - "time.*.gov"
    - "time.*.edu.cn"
    - "time.*.apple.com"
    - "time1.*.com"
    - "time2.*.com"
    - "time3.*.com"
    - "time4.*.com"
    - "time5.*.com"
    - "time6.*.com"
    - "time7.*.com"
    - ntp.ntsc.ac.cn
    - "ntp.*.com"
    - "ntp1.*.com"
    - "ntp2.*.com"
    - "ntp3.*.com"
    - "ntp4.*.com"
    - "ntp5.*.com"
    - "ntp6.*.com"
    - "ntp7.*.com"
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - "+.pool.ntp.org"
    - "time1.cloud.tencent.com"
    - "music.163.com"
    - "*.music.163.com"
    - "*.126.net"
    - "musicapi.taihe.com"
    - "music.taihe.com"
    - "songsearch.kugou.com"
    - "trackercdn.kugou.com"
    - "*.kuwo.cn"
    - "api-jooxtt.sanook.com"
    - "api.joox.com"
    - "joox.com"
    - "y.qq.com"
    - "*.y.qq.com"
    - "streamoc.music.tc.qq.com"
    - "mobileoc.music.tc.qq.com"
    - "isure.stream.qqmusic.qq.com"
    - "dl.stream.qqmusic.qq.com"
    - "aqqmusic.tc.qq.com"
    - "amobile.music.tc.qq.com"
    - "*.xiami.com"
    - "*.music.migu.cn"
    - "music.migu.cn"
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - "msftconnecttest.com"
    - "msftncsi.com"
    - "localhost.ptlogin2.qq.com"
    - "localhost.sec.qq.com"
    - "+.srv.nintendo.net"
    - "+.stun.playstation.net"
    - "xbox.*.microsoft.com"
    - "xnotify.xboxlive.com"
    - "+.battlenet.com.cn"
    - "+.wotgame.cn"
    - "+.wggames.cn"
    - "+.wowsgame.cn"
    - "+.wargaming.net"
    - "proxy.golang.org"
    - "stun.*.*"
    - "stun.*.*.*"
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "heartbeat.belkin.com"
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.router.asus.com"
    - "mesu.apple.com"
    - "swscan.apple.com"
    - "swquery.apple.com"
    - "swdownload.apple.com"
    - "swcdn.apple.com"
    - "swdist.apple.com"
    - "lens.l.google.com"
    - "stun.l.google.com"
    - "+.nflxvideo.net"
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
```
### 问题描述
由于配置文件中使用了Script，所以使用OpenClash的三种模式调用的都是TUN内核。
运行在Fake-IP模式下，当使用增强模式时，UDP走TProxy，此时测出来的NAT类型是Full cone NAT，如果使用TUN或者混合模式，UDP走TUN，那测出来的NAT类型就变成了Port-Restricted cone NAT。

如果关闭OpenWRT中的OpenClash，打开电脑上的Clash for Windows运行在TUN模式，此时UDP也走TUN，NAT类型测试下来是Full cone，在手机上运行Clash for Android，NAT类型也是Full Cone，所以应该不是TUN内核的问题。

### 测试截图
这是运行在增强模式下的NAT测试截图：
![Screenshot_2022-05-01-14-58-55-65_79c948626e09f93eabc8d1dd852bf261_Mosaic_15_1_40](https://user-images.githubusercontent.com/44701395/166135795-080fd283-3645-4fe4-9b68-50a1f2f375ec.jpg)

这是运行在TUN或混合模式下的NAT测试截图：
![Screenshot_2022-05-01-15-00-13-34_79c948626e09f93eabc8d1dd852bf261_Mosaic_15_1_29](https://user-images.githubusercontent.com/44701395/166135814-ca394d8f-5c0d-40ec-80a0-b3a23c6d2bd4.jpg)
