### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Lilies-of-the-valley** [vernesong/OpenClash#2750]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.51-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-armv8

### To Reproduce

DNS泄露测试链接：https://whoer.net/dns-leak-test

用以下在Clash for Windows处使用TUN模式运行无DNS泄露的简单配置：
```yaml
script:
  shortcuts:
    QUIC: network == 'udp' and dst_port == 443
rules:
- SCRIPT,QUIC,Quick UDP Internet Connections
- DOMAIN,localhost,DIRECT
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,0.0.0.0/8,DIRECT,no-resolve
- IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
- IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
- IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
- IP-CIDR,169.254.0.0/16,DIRECT,no-resolve
- IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
- IP-CIDR,192.0.0.0/24,DIRECT,no-resolve
- IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
- IP-CIDR,198.18.0.0/15,DIRECT,no-resolve
- IP-CIDR,224.0.0.0/3,DIRECT,no-resolve
- IP-CIDR6,::1/128,DIRECT,no-resolve
- IP-CIDR6,fc00::/7,DIRECT,no-resolve
- IP-CIDR6,fe80::/10,DIRECT,no-resolve
- MATCH,Proxy
hosts:
  s.caelumb.us: 202.91.34.210
dns:
  enable: true
  listen: 0.0.0.0:7874
  enhanced-mode: fake-ip
  use-hosts: true
  nameserver:
  - 223.5.5.5
  fallback: ['208.67.222.222:5353', '208.67.220.220:5353', '208.67.222.220:5353', '208.67.220.222:5353', 'https://1.1.1.1/dns-query', 'https://1.1.1.2/dns-query', 'https://1.1.1.3/dns-query', 'https://1.0.0.1/dns-query', 'https://1.0.0.2/dns-query', 'https://1.0.0.3/dns-query', 'https://45.11.45.11/dns-query', 'https://146.112.41.2/dns-query', 'https://162.159.36.1/dns-query', 'https://162.159.46.1/dns-query', 'https://9.9.9.11:5053/dns-query', 'https://101.6.6.6:8443/dns-query', 'https://208.67.222.222/dns-query', 'https://208.67.220.220/dns-query', 'https://185.222.222.222/dns-query', 'https://101.101.101.101/dns-query', 'https://149.112.112.11:5053/dns-query']
  fallback-filter:
    geoip: false
  ipv6: false
  fake-ip-range: 198.18.0.1/16
```

### Describe the Bug

预期行为：无DNS请求。但在试错调整了不少配置后始终无法避免DNS泄露
#563 #1007 两个相似的issues里无任何可用信息

### OpenClash Log

#此项有值时,如不使用IPv6,建议到网络-接口-lan的设置中禁用IPV6的DHCP
IPV6-DHCP: disabled

#此项结果应仅有配置文件的DNS监听地址
Dnsmasq转发设置: 127.0.0.1#7874

运行模式: fake-ip-tun
默认代理模式: rule
UDP流量转发(tproxy): 停用
DNS劫持: 启用
自定义DNS: 停用
IPV6代理: 停用
IPV6-DNS解析: 停用
禁用Dnsmasq缓存: 启用
自定义规则: 启用
仅允许内网: 启用
仅代理命中规则流量: 停用
仅允许常用端口流量: 停用
绕过中国大陆IP: 停用
DNS远程解析: 启用
路由本机代理: 启用

#启动异常时建议关闭此项后重试
混合节点: 停用
保留配置: 停用

#启动异常时建议关闭此项后重试
第三方规则: 停用

#===================== 自定义规则 一 =====================#
script:

rules:
- SRC-IP-CIDR,192.168.8.1/21,DIRECT,no-resolve

#===================== 自定义规则 二 =====================#

### Expected Behavior

现在是否能做到无DNS泄露？若否且无计划的话我就不继续投资时间在这一方面了。

痛点主要是我自己维护配置，并倾向国外服务，但一些在国内有可用IP的服务因为DNS解析而被`GEOIP,CN,Mainland China,no-resolve`直连了（比如Apple.com :'(）
