### ISSUE TITLE
[Bug] Custom rule doesn't take effect

### ISSUE THREAD

**Issue by rltyty** [vernesong/OpenClash#2882]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.70-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-armv7

### To Reproduce

我的机场配置默认是按IP分流的，但我需要指定部分国内网站走Proxy，部分国外网站走DIRECT，所以我尝试创建File type的Custom rule provider，并在Custom Rule Providers and Groups处添加，Append Position选择Priority match。

为了测试，我让youtube 走DIRECT，让一个国内的IP 查询网站走Proxy。

预期结果：1. youtube无法访问，2. IP查询的是代理的IP，而不是我本地的IP。
实际结果：1. youtube可以访问，2. IP查询依旧是我的本地IP

```
cat /etc/openclash/rule_provider/MyDIRECT.yaml
payload:
  # > My DIRECT
  - DOMAIN-SUFFIX,youtube.com
```

```
cat /etc/openclash/rule_provider/MyProxy.yaml
payload:
  # > My Proxy
  - DOMAIN-SUFFIX,ip111.cn
```

这是最后实际运行的配置节选

```
cat /etc/openclash/xxx.yaml
...
...
rules:
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- RULE-SET,MyDIRECT,DIRECT
- RULE-SET,MyProxy,Proxy
- DOMAIN-SUFFIX,googleapis.cn,Proxy
- DOMAIN,safebrowsing.urlsec.qq.com,DIRECT
...
...
rule-providers:
  MyDIRECT:
    type: file
    behavior: domain
    path: "./rule_provider/MyDIRECT.yaml"
  MyProxy:
    type: file
    behavior: domain
    path: "./rule_provider/MyProxy.yaml"
```

### Describe the Bug

自定义的策略没有生效。请问我该怎么进一步定位问题？

### OpenClash Log

在访问上述两个网站时，没有看到有意义的Debug Log。

### Expected Behavior

1. youtube无法访问，2. IP查询的是代理的IP，而不是我本地的IP。
