### ISSUE TITLE
[Feature] 当 config.yaml 的 rules 字段为空时，自动补充的本地业务逻辑会产生错误的描述文件。

### ISSUE THREAD

**Issue by zhyang-liu** [vernesong/OpenClash#3189]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 OpenClash 并不包含该功能特性或者还不完善
- [X] Framework 这是 OpenClash 应包含的特性, 并非 Clash 特性
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

当 config.yaml 的 rules 字段为空时，自动补充的本地业务逻辑会产生错误的描述文件。
例如如下配置文件，字段  `rules` 没有配置任何内容。
```yaml
# https://github.com/Dreamacro/clash/wiki/Configuration

mixed-port: 7890

mode: rule

external-controller: 127.0.0.1:9090

dns:
  enable: false

proxies:
  - name: "vmess"

proxy-groups:

proxy-providers:

rules:

```

此时，使用 `./clash -t -f ./config.yaml -d /root/clash-config` 进行测试时，会报告测试通过：  
`configuration file /etc/openclash/config.yaml test is successful`

但通过 openclash 启动该配置时，会提示配置错误：

```text
2023-04-15 14:45:06 Step 5: Check The Core Status...
time="2023-04-15T06:45:06Z" level=fatal msg="Parse config error: rules[3] ['SRC-IP-CIDR,198.18.0.1/16,DIRECT','SRC-IP-CIDR,192.168.10.2/32,DIRECT'] error: proxy [DIRECT'] not found"
```

注意到最后一串提示：`error: proxy [DIRECT'] not found` ，非常像通过“,”分段后获取了 proxy 名称为 `DIRECT'`，注意到最后多了一个单引号（'）。

**该问题在增加 rules 内容后，恢复正常**，增加 rules 后的配置内容是：

```yaml
# https://github.com/Dreamacro/clash/wiki/Configuration

mixed-port: 7890

mode: rule

external-controller: 127.0.0.1:9090

dns:
  enable: false

proxies:
  - name: "vmess"

proxy-groups:

proxy-providers:

rules:
  - DOMAIN-SUFFIX,google.com,vmess
```

### Describe the Solution

在修改补充本地代理规则前，如果数据结构中的rules为空，则先对该对象完成初始化，以规避上述检测问题。
