### ISSUE TITLE
[Bug] 使用“一键生成”界面编辑并应用配置会导致配置文件中出现格式错误(smux字段缩进缺失)

### ISSUE THREAD

**Issue by davidu2003** [vernesong/OpenClash#3289]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新 Dev 版本测试过，问题依旧存在
- [X] Core 这是 OpenClash 存在的问题，并非我所使用的 Clash 或 Meta 等内核的特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### OpenClash Version

v0.45.121-beta

### Bug on Environment

Official OpenWrt

### Bug on Platform

Linux-amd64(x86-64)

### To Reproduce

1. 进入“配置管理”页面，编辑当前配置，清空配置内容，输入"---"，保存，不应用。
2. 进入“一键生成”页面，编辑任意本地vmess节点，保存配置，应用配置。
3. 进入“配置管理”页面，查看当前运行配置文件。

### Describe the Bug

配置刚才编辑的节点会出现smux:字段缩进缺失导致配置文件格式不正确，如下：
```
- name: "节点名"
    type: vmess
    server: "serverip"
    port: 端口
    uuid: uuid
    alterId: 0
    cipher: auto
    udp: true
    xudp: true
    global-padding: false
    authenticated-length: false
    skip-cert-verify: true
    tls: false
    ip-version: "dual"
    tfo: true
  smux:
    enabled: false
```

### OpenClash Log

见上方bug描述

### Expected Behavior

在“一键生成”界面修改并应用配置能正确写入配置文件。

### Screenshots

<img width="386" alt="smux" src="https://github.com/vernesong/OpenClash/assets/127939717/62460c43-2668-40ce-bc99-7692602e175f">
