### ISSUE TITLE
NETFLIX显示代理，无法使用

### ISSUE THREAD

**Issue by k89898** [vernesong/OpenClash#33]
K3 OpenWrt v2.8 beta6 By stones运行后NETFLIX显示代理，直接PC使用Clash for Windows或软路由用KoolClash OpenWrt/LEDE无问题，求解决

**Comment by vernesong** [comment]
我这边fake-ip没问题。
```
redir-port: 7892
port: 7890
socks-port: 7891
mode: Rule
log-level: silent
external-controller: 0.0.0.0:9090
secret: "123456"
allow-lan: true
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
##Custom DNS##
  nameserver:
  - 114.114.114.114
  - 119.29.29.29
#===================== OpenClash-General-Settings =====================#
```
这种可能是节点那边dns解析问题导致的
