### ISSUE TITLE
[Feature] V大，meta已实现hy2的端口跳跃，能否添加该功能？！

### ISSUE THREAD

**Issue by zxlhhyccc** [vernesong/OpenClash#3786]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [X] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [X] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

meta已实现hy2的端口跳跃，希望添加该功能！
见：https://github.com/MetaCubeX/mihomo/commit/feedc9ec66b8afca3c76c82202cf9b7d69af3e75

**Comment by 666dechaoge** [comment]
更新了openclash meta alpha-gfeedc9e,现在原本正常hy2节点连不上上了，请问该如何配置

**Comment by RavenCage** [comment]
> 更新了openclash meta alpha-gfeedc9e,现在原本正常hy2节点连不上上了，请问该如何配置

我也是同样的问题，换回旧版一切正常。

**Comment by 666dechaoge** [comment]
> > 更新了openclash meta alpha-gfeedc9e,现在原本正常hy2节点连不上上了，请问该如何配置
> 
> 我也是同样的问题，换回旧版一切正常。

clash nyapasu使用alpha-feedc9e的内核，一样有问题，只能去找mihomo那边去解决了

**Comment by RavenCage** [comment]
> > > 更新了openclash meta alpha-gfeedc9e,现在原本正常hy2节点连不上上了，请问该如何配置
> > 
> > 
> > 我也是同样的问题，换回旧版一切正常。
> 
> clash nyanpasu使用alpha-feedc9e的内核，一样有问题，只能去找mihomo那边去解决了

我用的是clash verge 1.5.4一切正常。nyanpasu一直都有点问题，我早已弃用。

**Comment by 666dechaoge** [comment]
```yml
 #hysteria2
  - name: "hysteria2"
    type: hysteria2
    server: server.com
    port: 443
    #  up和down均不写或为0则使用BBR流控
    # up: "30 Mbps" # 若不写单位，默认为 Mbps
    # down: "200 Mbps" # 若不写单位，默认为 Mbps
    password: yourpassword
    # obfs: salamander # 默认为空，如果填写则开启obfs，目前仅支持salamander
    # obfs-password: yourpassword
    # sni: server.com
    # skip-cert-verify: false
    # fingerprint: xxxx
    # alpn:
    #   - h3
    # ca: "./my.ca"
    # ca-str: "xyz"
```
mihomo alpha文档给的示例还是旧的
