### ISSUE TITLE
[Feature] 添加对Meta内核listeners配置的支持，实现不同socks端口走不同代理

### ISSUE THREAD

**Issue by wsl-fd** [vernesong/OpenClash#3804]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

meta增加的listeners功能可以方便实现不同socks（或者其它入站协议）端口走不同代理的功能，比如：
```
listeners:
  #8085端口走直连
  - name: 'socks5-always-direct'
    type: socks   #也支持其它入站协议
    port: 8085
    proxy: DIRECT
```

而且，由于我这也有 #312 配置修改无法保存的问题，所以也没办法手动添加，，所以希望能在meta设置页面添加listeners配置，谢谢。
