### ISSUE TITLE
大佬，支持一下ssr可以不？

### ISSUE THREAD

**Issue by wclmgcd** [vernesong/OpenClash#393]
最近白嫖的两个GCP的v2和木马都出现问题，无奈买了个最便宜的机场，50g流量自己用来Google和tg，无奈只有ssr, 用回ssp+实在不习惯，lucia-app-clash和koolproxy有冲突，开启kp就网络不通，用openclash就没问题，自己把大佬的servers-config.lua修改后可以可以添加SSR，用clashr内核，无法启动提示time="2020-04-27T04:15:54Z" level=fatal msg="Parse config error: ProxyGroup[0]: 'hk10' not found"
2020-04-27 12:15:52 OpenClash Can Not Start, Please Check The Error Info And Try Again
time="2020-04-27T04:30:55Z" level=fatal msg="Parse config error: ProxyGroup[0]: 'hk10' not found"
2020-04-27 12:30:53 OpenClash Can Not Start, Please Check The Error Info And Try Again
hk10 就是ssr节点
<sub>发自[GeekHub](https://apps.apple.com/cn/app/id1476496206)</sub>

**Comment by wclmgcd** [comment]
[OpenWrt - LuCI.pdf](https://github.com/vernesong/OpenClash/files/4537602/OpenWrt.-.LuCI.pdf)

**Comment by pikachullk** [comment]
那你就把HK10给去掉不就行了...ssr在pull request那有人搞着~但是什么时候搞好不知道~

**Comment by wclmgcd** [comment]
> 那你就把HK10给去掉不就行了...ssr在clash核心的pull request那有人搞着~但是什么时候搞好不知道~

HK10就是ssr节点，添上ssr节点就无法启动

**Comment by pikachullk** [comment]
> > 那你就把HK10给去掉不就行了...ssr在clash核心的pull request那有人搞着~但是什么时候搞好不知道~
> 
> HK10就是ssr节点，添上ssr节点就无法启动

只能暂时不用～第二个支不支持ssr不是一个ui说了算～反映地方错了～要去clash核心那反映～而且已经在做了～别催了

**Comment by pikachullk** [comment]
还有clashR核心～要用也能临时顶上

**Comment by vernesong** [comment]
建议你使用代理集，把节点信息单独写进一个yaml后替换内核就可以使用插件全部功能
path: `/etc/openclash/proxy_provider/ssr.yaml`
节点信息格式和配置文件里的一样，ss的示例如下：
```
proxies:
- name: "ssr"
  type: ssr
  server: example.com
  port: 1234
  cipher: aes-128-gcm
  password: 123456
  udp: true
- name: "ss"
  type: ss
  server: example.com
  port: 1234
  cipher: aes-128-gcm
  password: 123456
  udp: true
  plugin: obfs
  plugin-opts:
    mode: tls
    host: example.com
```
