### ISSUE TITLE
[Feature] “代理集配置”请增加自定义User-Agent的选项

### ISSUE THREAD

**Issue by donnieYeh** [vernesong/OpenClash#4030]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

就如“配置订阅”功能可以自定义User-Agent一样，希望“代理集配置”也能支持该特性

配置路径：proxy-providers.header.User-Agent

```
proxy-providers:
  provider1:
    type: http
    url: "http://test.com"
    path: ./proxy_providers/provider1.yaml
    interval: 3600
    proxy: DIRECT
    header:
      User-Agent:
      - "Clash/v1.18.0"
      - "mihomo/1.18.3"
 ```
文档地址：https://wiki.metacubex.one/config/proxy-providers/
