### ISSUE TITLE
[Feature] 增加类似于clash verge rev中对订阅规则进行删改的功能

### ISSUE THREAD

**Issue by GoFightNow** [vernesong/OpenClash#4146]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经**使用最新 Dev 版本**查看过，并不包含该功能特性或者还不完善
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 应包含的特性
- [ ] Contributors 我有能力协助 OpenClash 开发或完善此功能特性
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### Describe the Feature

在看了几个dns防泄漏视频后，我发现现有的订阅使用的规则转换配置还算不错（[这是规则](https://cdn.jsdelivr.net/gh/Paofu-cloud/clashrules@main/clash.ini)）
但这个配置最后的GeoIP没有no-resolve，会导致无法匹配之前规则的链接直接进行dns请求，我想在这个规则之后添加no-resolve来使dns请求也由代理服务器发起。
在clash verge rev中，可以右键订阅->编辑规则，然后使用GUI或yml来删除新增规则，如下
```yaml
prepend: []
append:
  - 'GEOIP,CN,🎯 全球直连,no-resolve'
  - 'MATCH,🐟 漏网之鱼'
delete:
  - 'GEOIP,CN,🎯 全球直连'
  - 'MATCH,🐟 漏网之鱼'
```
尽管这个功能也只能在前或后添加，但恰巧能满足我的需求。

我在浏览Issues和wiki文档之后并未找到这种能快捷修改的方式，所以希望能有这种修改方式。
我认为可以在 覆写设置->规则设置->自定义规则 中实现，可以不光在前后增加规则，也可以根据全匹配删除规则。
也可以为更高级的用户提供正则表达直接进行替换（不重要，我是笨比）
