### ISSUE TITLE
[Bug] 自定义规则不识别rule-providers

### ISSUE THREAD

**Issue by LinusChen-yf** [vernesong/OpenClash#4213]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [X] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [X] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [X] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

v0.46.050-beta

### Bug on Environment

Istoreos

### OpenWrt Version

21.02.3

### Bug on Platform

Linux-arm64

### Describe the Bug

在自定义规则中使用rule-providers不被识别
报错2024-12-06 00:36:05 level=error msg="rules[3] [RULE-SET,applications,DIRECT] error: rule set [applications] not found"

### To Reproduce

在自定义规则中添加
```
rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,tld-not-cn,泡泡Dog
  - RULE-SET,gfw,泡泡Dog
  - RULE-SET,telegramcidr,泡泡Dog
  - MATCH,DIRECT
 ```

### OpenClash Log

```log
2024-12-06 00:36:05 level=error msg="rules[3] [RULE-SET,applications,DIRECT] error: rule set [applications] not found"
```

### Expected Behavior

能够支持rule-providers

**Comment by 7461151** [comment]
你为什么不直接编辑配置文件，添加你这些规则集呢？ 为什么非要在什么 自定义规则里面支持这种东西？ 或者规则附加也可以添加规则。 你这种不是下载规则集合吗? 自定义规则是 定义规则。 我作为第三者 看不下去了，这种要求

**Comment by LinusChen-yf** [comment]
不好意思 折腾了两个晚上 没在网上找到资料 所以来提问下
我尝试了覆写设置里的第三方规则和自定义规则都没起作用  我以为可以跟clash verge一眼merge rule
我去试试规则附加  谢谢你们@7461151 @fejeIaqbhbv

**Comment by LinusChen-yf** [comment]
成功了 谢谢  在规则附加里面一条一条添加到规则集里然后在自定义规则添加这些规则就成功了
```
rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
......
```

但是有没有更方便的方法能将一整个rule-providers配置导入进去  我尝试将包含rule-providers的文件添加到规则集文件里  但是这样并不会起效果
