### ISSUE TITLE
[Bug] 出现非预期DNS解析

### ISSUE THREAD

**Issue by utopeadia** [vernesong/OpenClash#4362]
### Verify Steps

- [x] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [x] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [x] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [x] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

0.46.075

### Bug on Environment

Lean

### OpenWrt Version

	QWRT R25.2.5

### Bug on Platform

Linux-amd64(x86-64)

### Describe the Bug

故事的起因是看日志的时候注意到有一些对google.com的dns请求，按照mihomo的逻辑，对于匹配到域名规则的内容应该不会触发本地解析而是会交给代理服务器解析，于是猜测可能是IP规则存在问题（比如高优先级忘了加no-resolve），于是将所有的rules改为了下面的简化形式 (dns配置为直接复制运行时dns设置)：
```
tun:
  enable: true
  stack: system
  device: utun
  dns-hijack:
  - 127.0.0.1:53
  endpoint-independent-nat: true
  auto-route: false
  auto-detect-interface: false
  auto-redirect: false
  strict-route: false
dns:
  enable: true
  ipv6: true
  prefer-h3: true
  use-hosts: true
  nameserver-policy:
    geosite:googlefcm:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    geosite:gfw:
    - https://8.8.8.8/dns-query
    - https://1.1.1.1/dns-query
    www.msftconnecttest.com:
    - 119.29.29.29
    - 223.5.5.5
    dns.msftncsi.com:
    - 119.29.29.29
    - 223.5.5.5
    www.msftncsi.com:
    - 119.29.29.29
    - 223.5.5.5
  default-nameserver:
  - 119.29.29.29
  - 223.5.5.5
  direct-nameserver:
  - 119.29.29.29
  - 223.5.5.5
  - dhcp://en0
  nameserver:
  - 119.29.29.29
  - 223.5.5.5
  - dhcp://en0
  fallback:
  - https://8.8.8.8/dns-query
  - https://1.1.1.1/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
    - 240.0.0.0/4
```
```
rules:
  - GEOSITE,cn,🚄 本地直连
  - GEOSITE,gfw,⚡️ 主要代理
  - GEOIP,CN,🚄 本地直连
  - MATCH,🐟 漏网之鱼
```
在这个配置中，命中geosite,gfw的规则按照要求应该交给代理服务器解析的，有意思的来了，在oc中，访问www.github.com发现进行了DNS解析
```
[2025-03-04 21:54:27][DEBUG] [DNS] resolve www.github.com AAAA from https://1.1.1.1:443/dns-query
[2025-03-04 21:54:27][DEBUG] [DNS] resolve www.github.com A from https://1.1.1.1:443/dns-query
[2025-03-04 21:54:27][DEBUG] [DNS] resolve www.github.com A from https://8.8.8.8:443/dns-query
[2025-03-04 21:54:27][DEBUG] [DNS] resolve www.github.com AAAA from https://8.8.8.8:443/dns-query
[2025-03-04 21:54:27][DEBUG] [DNS] resolve www.github.com HTTPS from https://1.1.1.1:443/dns-query
[2025-03-04 21:54:27][DEBUG] [DNS] resolve www.github.com HTTPS from https://8.8.8.8:443/dns-query
```
原本猜测是因为内核原因导致问题，遂在客户设备使用clash verge rev+mihomo1.19.3抓取访问情况，结果发现cvr的日志中没有找到对应的解析（也就是符合预期，因为这个dns不应该解析），在cvr中：
```
www.github.com:443 match GeoSite(gfw) using ⚡️ 主要代理[xxxxx]
```
请问大佬对这个问题有没有可能的猜测

### To Reproduce

同Describe说明

### OpenClash Log

```log
同Describe说明
```

### OpenClash Config

```shell

```

### Expected Behavior

域名规则匹配内容应交付匹配规则对应节点进行连接

**Comment by Harrison-LUO** [comment]
same issus

**Comment by Harrison-LUO** [comment]
same issue

**Comment by fanybook** [comment]
今天别的 clash 都没事，passwell 也没事，就 openclash 不行了

**Comment by vernesong** [comment]
你发运行配置

**Comment by utopeadia** [comment]
> 今天别的 clash 都没事，passwall 也没事，就 openclash 不行了

你这个问题是因为昨天开会非域名大量非域名境外DNS被ban导致的，跟我这个不太一样，我这个是触发了不应该出现的解析，按照mihomo文档，对于域名规则应该直接出站由代理服务器解析而不是本地解析

**Comment by utopeadia** [comment]
> 你发运行配置

这是我直接复制的运行配置，仅溢出了代理配置
```
---
port: 7890
socks-port: 7891
mixed-port: 7893
allow-lan: true
bind-address: "*"
ipv6: true
external-controller: 0.0.0.0:9090
mode: rule
log-level: info
global-client-fingerprint: chrome
global-ua: mihomo
unified-delay: false
geodata-mode: true
geo-auto-update: true
geo-update-interval: 12
geox-url:
  geoip: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip-lite.dat
  geosite: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
  mmdb: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country-lite.mmdb
  asn: https://testingcf.jsdelivr.net/gh/xishang0128/geoip@release/GeoLite2-ASN.mmdb
tun:
  enable: true
  stack: system
  device: utun
  dns-hijack:
  - 127.0.0.1:53
  endpoint-independent-nat: true
  auto-route: false
  auto-detect-interface: false
  auto-redirect: false
  strict-route: false
dns:
  enable: true
  ipv6: true
  prefer-h3: true
  use-hosts: true
  nameserver-policy:
    geosite:googlefcm:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    www.msftconnecttest.com:
    - 119.29.29.29
    - 223.5.5.5
    dns.msftncsi.com:
    - 119.29.29.29
    - 223.5.5.5
    www.msftncsi.com:
    - 119.29.29.29
    - 223.5.5.5
  default-nameserver:
  - 119.29.29.29
  - 223.5.5.5
  nameserver:
  - 119.29.29.29
  - 223.5.5.5
  - dhcp://en0
  proxy-server-nameserver:
  - 121.251.251.251
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://dns.google/dns-query#RULES
  - tls://1.1.1.1#RULES
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
    - 240.0.0.0/4
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
  - geosite:cn
  - "*"
  - "+.lan"
  - connect.rom.miui.com
  - kuxueyun.com
  - "+.miwifi.com"
  - "+.ntp.org"
  - "+.u-tools.cn"
  - "+.mediatek.com"
  - "+.cfprefer1.xyz"
  - "+.wetab.link"
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  - "+.weixin.qq.com"
  - "+.wechat.com"
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - "+.wpsmail.net"
  - "+.henzanapp.com"
  - "+.pconline.com.cn"
  - "+.kuxueyun.com"
  - ntp.*.com
  - time.windows.com
  - time.nist.gov
  - time.apple.com
  - time.asia.apple.com
  - cn.ntp.org.cn
  - edu.ntp.org.cn
  - hk.ntp.org.cn
  - tw.ntp.org.cn
  - us.ntp.org.cn
  - sgp.ntp.org.cn
  - kr.ntp.org.cn
  - jp.ntp.org.cn
  - de.ntp.org.cn
  - ina.ntp.org.cn
  - 0.openwrt.pool.ntp.org
  - 1.openwrt.pool.ntp.org
  - 2.openwrt.pool.ntp.org
  - 3.openwrt.pool.ntp.org
  - ntp.aliyun.com
  - ntp1.aliyun.com
  - ntp2.aliyun.com
  - ntp3.aliyun.com
  - ntp4.aliyun.com
  - ntp5.aliyun.com
  - ntp6.aliyun.com
  - ntp7.aliyun.com
  - time1.aliyun.com
  - time2.aliyun.com
  - time3.aliyun.com
  - time4.aliyun.com
  - time5.aliyun.com
  - time6.aliyun.com
  - time7.aliyun.com
  - s1c.time.edu.cn
  - s2m.time.edu.cn
  - s1b.time.edu.cn
  - s1e.time.edu.cn
  - s2a.time.edu.cn
  - s2b.time.edu.cn
  - time1.apple.com
  - time2.apple.com
  - time3.apple.com
  - time4.apple.com
  - time5.apple.com
  - time6.apple.com
  - time7.apple.com
  - time1.google.com
  - time2.google.com
  - time3.google.com
  - time4.google.com
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  override-destination: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080-8880
      override-destination: true
    TLS:
      ports:
      - 443
      - 8443
      override-destination: true
    QUIC:
      ports:
      - 443
      - 8443
      override-destination: true
  force-domain:
  - "+.v2ex.com"
  - "+.google.com"
  skip-domain:
  - Mijia Cloud
  - ntp.aliyun.com
  - dlg.io.mi.com
  - time.windows.com
  - time.apple.com
  - "+.apple.com"
  - "+.rc.sunlogin.net"
  - courier.push.apple.com
  - rbsxbxp-mim.vivox.com
  - rbsxbxp.www.vivox.com
  - rbsxbxp-ws.vivox.com
  - rbspsxp.www.vivox.com
  - rbspsxp-mim.vivox.com
  - rbspsxp-ws.vivox.com
  - rbswxp.www.vivox.com
  - rbswxp-mim.vivox.com
  - disp-rbspsp-5-1.vivox.com
  - disp-rbsxbp-5-1.vivox.com
  - proxy.rbsxbp.vivox.com
  - proxy.rbspsp.vivox.com
  - proxy.rbswp.vivox.com
  - rbswp.vivox.com
  - rbsxbp.vivox.com
  - rbspsp.vivox.com
  - rbspsp.www.vivox.com
  - rbswp.www.vivox.com
  - rbsxbp.www.vivox.com
  - rbsxbxp.vivox.com
  - rbspsxp.vivox.com
  - rbswxp.vivox.com
  - basic-static-server.infinitynewtab.com
  force-dns-mapping: true
  parse-pure-ip: false
  skip-dst-address:
  - 223.5.5.5/32
  - 223.6.6.6/32
  - 119.29.29.29/32
  - 1.1.1.1/32
  - 8.8.8.8/32
  - 110.242.69.63/32
  - 221.194.154.187/32
  - 36.248.45.62/32
  - 2001:4860:4860::8888/128
  - 2001:4860:4860::8844/128
hosts:
  mtalk.google.com: 74.125.204.188
  alt1-mtalk.google.com: 142.251.2.188
  alt2-mtalk.google.com: 192.178.128.188
  alt3-mtalk.google.com: 108.177.104.188
  alt4-mtalk.google.com: 108.177.104.188
  alt5-mtalk.google.com: 142.250.141.188
  alt6-mtalk.google.com: 173.194.77.188
  alt7-mtalk.google.com: 173.194.219.188
  alt8-mtalk.google.com: 142.250.112.188
rules:
- "GEOSITE,cn,\U0001F684 本地直连"
- GEOSITE,gfw,⚡️ 主要代理
- "GEOIP,CN,\U0001F684 本地直连"
- "MATCH,\U0001F41F 漏网之鱼"
redir-port: 7892
tproxy-port: 7895
external-ui: "/usr/share/openclash/ui"
keep-alive-interval: 15
keep-alive-idle: 600
geodata-loader: memconservative
tcp-concurrent: true
find-process-mode: strict
```
注意到github.com后缀能触发geosite:gfw内容，但是仍然存在相关的解析，按照逻辑不应该触发解析才对
![Image](https://github.com/user-attachments/assets/d1d94ef8-2d09-4b19-8bae-9be79c4525ee)

![Image](https://github.com/user-attachments/assets/bc29d730-568d-4cd0-86c8-c837ab52f6e3)

![Image](https://github.com/user-attachments/assets/415420af-1e0d-4b3b-9988-166a3e3cfd6d)

![Image](https://github.com/user-attachments/assets/9f1418db-0261-4a75-8b78-c38646568fd5)
