### ISSUE TITLE
[Bug] 启动openclash后无法使用国外DNS查询域名

### ISSUE THREAD

**Issue by edison0354** [vernesong/OpenClash#4384]
### Verify Steps

- [x] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] Branch 我知道 OpenClash 的 Dev 分支切换开关位于插件设置-版本更新中，或者我会手动下载并安装 Dev 分支的 OpenClash
- [x] Latest 我已经**使用最新 Dev 版本**测试过，问题依旧存在
- [x] Relevant 我知道 OpenClash 与 内核(Core)、控制面板(Dashboard)、在线订阅转换(Subconverter)等项目之间**无直接关系**，仅相互调用
- [x] Definite 这确实是 OpenClash 出现的问题
- [ ] Contributors 我有能力协助 OpenClash 开发并解决此问题
- [ ] Meaningless 我提交的**是无意义的**催促更新或修复请求

### OpenClash Version

OpenClash: v0.46.080; Meta: alpha-gdee5898

### Bug on Environment

Official OpenWrt

### OpenWrt Version

24.10.0

### Bug on Platform

Linux-arm64

### Describe the Bug

* OpenClash内置DNS全为国外Server时，完全无法解析任何域名
   * 初衷是全局国外DNS，然后给国内域名设policy
* 此时在电脑上手动`dig dns.google.com @223.5.5.5`，无法查询到结果
   * 但ssh到路由器上dig会有正确返回
   * 关掉OpenClash，直接在电脑上dig也有正确返回
* 但在以上不可用的状态下，只要nameserver增加任何一个阿里/腾讯DNS即可正常使用
   * 也是填域名`https://doh.pub/dns-query`，而并非IP，感觉原始default-nameserver应该也没问题

### To Reproduce

配置如下，测试问题把其他所有规则都关了，跑的配置里只有节点信息以及如下一小段。
```
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
  - tls://dns.google
  - https://dns.google/dns-query
  - tls://1dot1dot1dot1.cloudflare-dns.com
  - https://cloudflare-dns.com/dns-query
  - https://doh.opendns.com/dns-query
  default-nameserver:
  - 119.29.29.29
  - 223.5.5.5
redir-port: 7892
tproxy-port: 7895
mixed-port: 7893
secret: ***********
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
keep-alive-interval: 15
keep-alive-idle: 600
ipv6: false
profile:
  store-selected: true
```

无返回的dig信息：
```
; <<>> DiG 9.10.6 <<>> dns.google.com @223.5.5.5
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 42593
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;dns.google.com.			IN	A

;; Query time: 1 msec
;; SERVER: 223.5.5.5#53(223.5.5.5)
;; WHEN: Sun Mar 16 20:15:16 CST 2025
;; MSG SIZE  rcvd: 32
```

### OpenClash Log

```log
🈚️
```

### OpenClash Config

```shell

```

### Expected Behavior

可正常查询DNS
