### ISSUE TITLE
启动脚本中yml_模块修改proxy-providers:时会去掉所有的‘’导致运行出错

### ISSUE THREAD

**Issue by Mosney** [vernesong/OpenClash#506]
```yml

启动脚本修改后：
proxy-providers:
   provider1: {type: http, url: http://hostname.tld/getprofile?name=profilename&token=token, interval: 3600, path: ./provider.yaml, health-check: {enable: true, interval: 600, url: http://cp.cloudflare.com/generate_204}}

应为：
proxy-providers:
   'provider1': {type: http, url: 'http://hostname.tld/getprofile?name=profilename&token=token', interval: 3600, path: ./provider.yaml, health-check: {enable: true, interval: 600, url: 'http://cp.cloudflare.com/generate_204'}}
```
