### ISSUE TITLE
Fake-ip 模式下，电脑启动后会一直显示无法连接到 Internet

### ISSUE THREAD

**Issue by HueLiu** [vernesong/OpenClash#6]
路由器下所有的设备均可正常连接外网，但是两台 Windows 设备在重启电脑后，网络图标均提示会一直显示无法连接到 Internet，但实际上是可以正常上网的及连接外网。

当重启 OpenClash 后，两台电脑才会恢复到正常的已联网图标。

路由器固件是 Lean Openwrt，配置文件中的端口及 DNS 设置如下:

```
port: 7890
socks-port: 7891
external-ui: "/usr/share/openclash/dashboard"
secret: '123456'
redir-port: 7892
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:7874
  enhanced-mode: fake-ip
  nameserver:
    - 119.28.28.28
    - 119.29.29.29
    - 182.254.116.116
```

请问这个问题是 Clash 本体的问题，还是 OpenClash 的问题？谢谢~
