### ISSUE TITLE
更新完clash内核后兼容模式无法科学上网，TUN模式可以正常科学上网

### ISSUE THREAD

**Issue by STIVW** [vernesong/OpenClash#605]
今天更新了clash内核，更新了订阅文件后。

兼容模式无法科学上网，国内流量正常上网。

TUN模式可以正常科学上网。（配置文件应该不会有问题吧。）

**Comment by harryhpxs** [comment]
同上，clash内核 v1.0.0-11-gae1e1dc (armv8) 兼容模式无法正常科学上网。
回退到 [v1.0.0-6-ge6aa452](https://github.com/vernesong/OpenClash/releases/tag/v0.39.3-beta) 后正常。

**Comment by STIVW** [comment]
我也打算回到旧版。但是没找到旧版的包？求给个链接

**Comment by harryhpxs** [comment]
> 
> 
> 我也打算回到旧版。但是没找到旧版的包？求给个链接

我上面有放链接啊
https://github.com/vernesong/OpenClash/releases/tag/v0.39.3-beta

**Comment by STIVW** [comment]
> > 我也打算回到旧版。但是没找到旧版的包？求给个链接
> 
> 我上面有放链接啊
> https://github.com/vernesong/OpenClash/releases/tag/v0.39.3-beta

好的，谢谢！我以为这里只有客户端的包所以没仔细看。

**Comment by yang05130** [comment]
我倒是可以上，就是用一段时间后，上传速度会被限得很低

**Comment by OUZYcn** [comment]
当前【TUN模式】内核版本 | 2020.07.11.gfce03ee
当前客户端版本 | v0.39.4-beta

搭车报个疑似bug，“全局设置” - “DNS设置” - “高级设置”：停用 或者 启用。 

Fake-IP域名黑名单 依然在config.yaml文件中

```
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  **fake-ip-filter:**
##Custom fake-ip-filter##
  - '*.lan'
  - 'time.windows.com'
  - 'time.nist.gov'
  - 'time.apple.com'
  - 'time.asia.apple.com'
  - '*.ntp.org.cn'
  - '*.openwrt.pool.ntp.org'
  - 'time1.cloud.tencent.com'
  - 'time.ustc.edu.cn'
  - 'pool.ntp.org'
  - 'ntp.ubuntu.com'
  - 'ntp.aliyun.com'
  - 'ntp1.aliyun.com'
  - 'ntp2.aliyun.com'
  - 'ntp3.aliyun.com'
  - 'ntp4.aliyun.com'
  - 'ntp5.aliyun.com'
  - 'ntp6.aliyun.com'
  - 'ntp7.aliyun.com'
  - 'time1.aliyun.com'
  - 'time2.aliyun.com'
  - 'time3.aliyun.com'
  - 'time4.aliyun.com'
  - 'time5.aliyun.com'
  - 'time6.aliyun.com'
  - 'time7.aliyun.com'
  - '*.time.edu.cn'
  - 'time1.apple.com'
  - 'time2.apple.com'
  - 'time3.apple.com'
  - 'time4.apple.com'
  - 'time5.apple.com'
  - 'time6.apple.com'
  - 'time7.apple.com'
  - 'time1.google.com'
  - 'time2.google.com'
  - 'time3.google.com'
  - 'time4.google.com'
  - 'music.163.com'
  - '*.music.163.com'
  - '*.126.net'
  - 'musicapi.taihe.com'
  - 'music.taihe.com'
  - 'songsearch.kugou.com'
  - 'trackercdn.kugou.com'
  - '*.kuwo.cn'
  - 'api-jooxtt.sanook.com'
  - 'api.joox.com'
  - 'joox.com'
  - 'y.qq.com'
  - '*.y.qq.com'
  - 'streamoc.music.tc.qq.com'
  - 'mobileoc.music.tc.qq.com'
  - 'isure.stream.qqmusic.qq.com'
  - 'dl.stream.qqmusic.qq.com'
  - 'aqqmusic.tc.qq.com'
  - 'amobile.music.tc.qq.com'
  - '*.xiami.com'
  - '*.music.migu.cn'
  - 'music.migu.cn'
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - 'localhost.ptlogin2.qq.com'
  - '*.*.*.srv.nintendo.net'
  - '*.*.stun.playstation.net'
  - 'xbox.*.*.microsoft.com'
  - '*.*.xboxlive.com'
##Custom fake-ip-filter END##

```
