### ISSUE TITLE
OpenClash对部分机场订阅配置中的DNS字段无法正常解析。。。。。

### ISSUE THREAD

**Issue by caliban511** [vernesong/OpenClash#836]
如题。
跟机场反馈了下，但机场那边表示不是他们的问题。
而且在Clash for Windows中，以及其它安卓客户端中都一切正常，所以是OpenClash问题的可能性更大些。。。
日志如下：
```
2020-10-09 23:11:07 Config 【upear】 Update Successful
2020-10-09 23:11:27 Nameserver Must Be Set, Please Change Your Configrations In Config.yaml
```
机场配置中的DNS段内容如下：
```
dns:
    enable: true
    ipv6: true
    enhanced-mode: redir-host
    nameserver: [119.29.29.29, 223.5.5.5]
    fallback: ['tls://1.0.0.1:853', 'https://doh.rixcloud.dev/dns-query']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4] }
```
每次用用openclash更新订阅后都会因为这一段无法识别和自动替换而导致软件启动失败，只能手动修改。
希望大佬能给适配一下。
