### ISSUE TITLE
[bug] 0.40.8 changes `proxies:` to `Proxy:`

### ISSUE THREAD

**Issue by maddie** [vernesong/OpenClash#840]
In this part of the script:

https://github.com/vernesong/OpenClash/blob/8bced085c860d9bcaac0887e1e3caadaaa034317/luci-app-openclash/root/usr/share/openclash/yml_field_name_ch.sh#L23-L27

... it changes the new format `proxies:` to old `Proxy:`, causing clash not able to find proxies defined in `proxy-groups`.

Is this intentional?

**Comment by vernesong** [comment]
provide your config file for test

**Comment by maddie** [comment]
Here's redacted config:

```
redir-port: 7892
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
tun:
  enable: true
  stack: system
  macOS-auto-route: true
  dns-hijack:
  - 8.8.8.8:53
  - tcp://8.8.8.8:53
hosts:
  mtalk.google.com: 108.177.125.188
  t.cn: 203.107.55.116
dns:
  enable: true
  listen: 0.0.0.0:1053
  default-nameserver:
  - 114.114.114.114
  - 8.8.8.8
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - www.example.com'
  nameserver:
  - 1.2.4.8
  - 114.114.114.114
  - 223.5.5.5
  - tls://dns.rubyfish.cn:853
  - https://1.1.1.1/dns-query
  fallback:
  - tls://1.0.0.1:853
  - tls://dns.google:853
  - tls://dns.rubyfish.cn:853
  - https://1.1.1.1/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
    - 0.0.0.0/32
proxies:
- name: "server 1"
  type: trojan
  server: www.example.com
  port: 443
  alterId: 0
  udp: true
  servername: ""
  password: hunter2
  sni: www.example.com
  alpn:
  - h2
- name: "server 2"
  type: trojan
  server: www.example.com
  port: 443
  alterId: 0
  udp: true
  servername: ""
  password: hunter2
  sni: www.example.com
  alpn:
  - h2
- name: "server 3"
  type: trojan
  server: www.example.com
  port: 443
  alterId: 0
  udp: true
  servername: ""
  password: hunter2
  sni: www.example.com
  alpn:
  - h2
- name: "server 4"
  type: trojan
  server: www.example.com
  port: 443
  alterId: 0
  udp: true
  servername: ""
  password: hunter2
  sni: www.example.com
  alpn:
  - h2
- name: "server 5"
  type: trojan
  server: www.example.com
  port: 443
  alterId: 0
  udp: true
  servername: ""
  password: hunter2
  sni: www.example.com
  alpn:
  - h2
- name: "server 6"
  type: trojan
  server: www.example.com
  port: 443
  alterId: 0
  udp: true
  servername: ""
  password: hunter2
  sni: www.example.com
  alpn:
  - h2
- name: "server 7"
  type: trojan
  server: www.example.com
  port: 443
  alterId: 0
  udp: true
  servername: ""
  password: hunter2
  sni: www.example.com
  alpn:
  - h2
- name: "server 8"
  type: trojan
  server: www.example.com
  port: 443
  alterId: 0
  udp: true
  servername: ""
  password: hunter2
  sni: www.example.com
  alpn:
  - h2
proxy-groups:
- name: UrlTest
  type: url-test
  proxies:
  - "server 1"
  - "server 2"
  - "server 3"
  - "server 4"
  - "server 5"
  - "server 6"
  - "server 7"
  - "server 8"
  url: http://connectivitycheck.gstatic.com/generate_204
  interval: 300
- name: PROXY
  type: select
  proxies:
  - UrlTest
  - "server 1"
  - "server 2"
  - "server 3"
  - "server 4"
  - "server 5"
  - "server 6"
  - "server 7"
  - "server 8"
- name: MATCH
  type: select
  proxies:
  - PROXY
  - DIRECT
- name: Streaming
  type: select
  proxies:
  - PROXY
  - "server 1"
  - "server 2"
  - "server 3"
  - "server 4"
  - "server 5"
  - "server 6"
  - "server 7"
  - "server 8"
- name: StreamingSE
  type: select
  proxies:
  - DIRECT
  - PROXY
rule-providers:
  China:
    type: http
    behavior: classical
    path: ./RuleSet/China.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml
    interval: 86400
  ChinaIP:
    type: http
    behavior: ipcidr
    path: ./RuleSet/Extra/ChinaIP.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/ChinaIP.yaml
    interval: 86400
  Global:
    type: http
    behavior: classical
    path: ./RuleSet/Global.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Global.yaml
    interval: 86400
  Netflix:
    type: http
    behavior: classical
    path: ./RuleSet/Netflix.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Video/Netflix.yaml
    interval: 86400
  Streaming:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/Streaming.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Streaming.yaml
    interval: 86400
  StreamingSE:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/StreamingSE.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingSE.yaml
    interval: 86400
  Unbreak:
    type: http
    behavior: classical
    path: ./RuleSet/Unbreak.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Unbreak.yaml
    interval: 86400
rules:
- RULE-SET,Unbreak,DIRECT
- RULE-SET,Streaming,Streaming
- RULE-SET,StreamingSE,StreamingSE
- RULE-SET,Global,PROXY
- RULE-SET,China,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- IP-CIDR,224.0.0.0/4,DIRECT
- GEOIP,CN,DIRECT
- MATCH,MATCH

```
