### ISSUE TITLE
[bug] fails to start when `macOS-auto-route` exists under `tun` section

### ISSUE THREAD

**Issue by maddie** [vernesong/OpenClash#841]
The config has the following `tun` section:

```
tun:
  enable: true
  stack: system
  macOS-auto-route: true
  dns-hijack:
  - 8.8.8.8:53
  - tcp://8.8.8.8:53
```

Note the `macOS-auto-route` attribute.

When OpenClash applies the changes to the script, the `macOS-auto-route` doesn't get moved into the changed `tun` section, instead, it's left behind with indentation, causing error:

```
time="2020-10-12T08:33:58Z" level=fatal msg="Parse config error: yaml: line 9: mapping values are not allowed in this context"
```
