### ISSUE TITLE
trojan 订阅时，生成的 clash 配置文件不正确

### ISSUE THREAD

**Issue by zhengcan** [vernesong/OpenClash#873]
我有一个 trojan 订阅，里面有如下部分
```
proxies:
    - {type: trojan, name: 'xxxxxxx', server: 'xxx.xxx.xxx.xxx', port: 443, password: 'xxxx', sni: 'xxx.xxx.xxx', skip-cert-verify: true}
```

在导入之后，生成的 clash 如下：
```
Proxy:
  - name: "xxxxxxx"
    type: trojan
    server: xxx.xxx.xxx.xxx
    port: 443
    password: "xxxx"
    sni: xxx.xxx.xxx
    alpn:
      - {type:
      - trojan
    skip-cert-verify: true
```

其中有一个 `alpn: - {type:` 导致 clash 加载失败
还请看一下这是怎么回事
